##Q2 TRANSITION MOMENTS
from . import logger

def compute_TY__q2_h1__CCEE(mr_adc, Y_KLCD, TY):

    cput1 = (logger.process_clock(), logger.perf_counter())

    # Einsum definition from kernel
    einsum = mr_adc.interface.einsum
    einsum_type = mr_adc.interface.einsum_type

    # Dimensions
    s_c = 0
    f_c = s_c + mr_adc.ncvs
    s_v = f_c
    f_v = s_v + mr_adc.nval
    s_a = f_v
    f_a = s_a + mr_adc.ncas
    s_e = f_a
    f_e = s_e + mr_adc.nextern
 
    ## Amplitudes
    t1_xa = mr_adc.t1.xa
    t1_va = mr_adc.t1.va
    t1_xe = mr_adc.t1.xe
    t1_ve = mr_adc.t1.ve
    t1_ae = mr_adc.t1.ae

    t1_xxaa = mr_adc.t1.xxaa
    t1_xxae = mr_adc.t1.xxae
    t1_xxee = mr_adc.t1.xxee

    t1_xvae = mr_adc.t1.xvae
    t1_xvee = mr_adc.t1.xvee

    t1_xaaa = mr_adc.t1.xaaa
    t1_xaae = mr_adc.t1.xaae
    t1_xaea = mr_adc.t1.xaea
    t1_xaee = mr_adc.t1.xaee

    t1_vxaa = mr_adc.t1.vxaa
    t1_vxae = mr_adc.t1.vxae
    t1_vxee = mr_adc.t1.vxee

    t1_vaaa = mr_adc.t1.vaaa
    t1_vaae = mr_adc.t1.vaae
    t1_vaea = mr_adc.t1.vaea
    t1_vaee = mr_adc.t1.vaee

    t1_aaae = mr_adc.t1.aaae
    t1_aaee = mr_adc.t1.aaee

    # Reduced Density Matrices
    rdm_ca = mr_adc.rdm.ca

    temp =- 1/2 * einsum('RPiab,Qixa,xb->RPQ', Y_KLCD, t1_xxae, t1_ae, optimize = einsum_type)
    temp += einsum('RPiab,Qixb,xa->RPQ', Y_KLCD, t1_xxae, t1_ae, optimize = einsum_type)
    temp += einsum('RPiab,Qixy,xyab->RPQ', Y_KLCD, t1_xxaa, t1_aaee, optimize = einsum_type)
    temp -= 1/2 * einsum('RPiab,Qixy,yxab->RPQ', Y_KLCD, t1_xxaa, t1_aaee, optimize = einsum_type)
    temp += einsum('RPiab,iQxa,xb->RPQ', Y_KLCD, t1_xxae, t1_ae, optimize = einsum_type)
    temp -= 1/2 * einsum('RPiab,iQxb,xa->RPQ', Y_KLCD, t1_xxae, t1_ae, optimize = einsum_type)
    temp -= einsum('RPiab,ix,Qxab->RPQ', Y_KLCD, t1_xa, t1_xaee, optimize = einsum_type)
    temp += 1/2 * einsum('RPiab,ix,Qxba->RPQ', Y_KLCD, t1_xa, t1_xaee, optimize = einsum_type)
    temp -= 1/2 * einsum('RPiab,ixab,Qx->RPQ', Y_KLCD, t1_xaee, t1_xa, optimize = einsum_type)
    temp += einsum('RPiab,ixba,Qx->RPQ', Y_KLCD, t1_xaee, t1_xa, optimize = einsum_type)
    temp += 1/4 * einsum('RPiab,Qixa,xyzb,zy->RPQ', Y_KLCD, t1_xxae, t1_aaae, rdm_ca, optimize = einsum_type)
    temp -= 1/2 * einsum('RPiab,Qixa,yxzb,zy->RPQ', Y_KLCD, t1_xxae, t1_aaae, rdm_ca, optimize = einsum_type)
    temp -= 1/2 * einsum('RPiab,Qixb,xyza,zy->RPQ', Y_KLCD, t1_xxae, t1_aaae, rdm_ca, optimize = einsum_type)
    temp += einsum('RPiab,Qixb,yxza,zy->RPQ', Y_KLCD, t1_xxae, t1_aaae, rdm_ca, optimize = einsum_type)
    temp -= 1/2 * einsum('RPiab,Qixy,xzab,yz->RPQ', Y_KLCD, t1_xxaa, t1_aaee, rdm_ca, optimize = einsum_type)
    temp += 1/4 * einsum('RPiab,Qixy,yzab,xz->RPQ', Y_KLCD, t1_xxaa, t1_aaee, rdm_ca, optimize = einsum_type)
    temp += 1/4 * einsum('RPiab,Qixy,zxab,yz->RPQ', Y_KLCD, t1_xxaa, t1_aaee, rdm_ca, optimize = einsum_type)
    temp -= 1/2 * einsum('RPiab,Qixy,zyab,xz->RPQ', Y_KLCD, t1_xxaa, t1_aaee, rdm_ca, optimize = einsum_type)
    temp -= 1/2 * einsum('RPiab,iQxa,xyzb,zy->RPQ', Y_KLCD, t1_xxae, t1_aaae, rdm_ca, optimize = einsum_type)
    temp += einsum('RPiab,iQxa,yxzb,zy->RPQ', Y_KLCD, t1_xxae, t1_aaae, rdm_ca, optimize = einsum_type)
    temp += 1/4 * einsum('RPiab,iQxb,xyza,zy->RPQ', Y_KLCD, t1_xxae, t1_aaae, rdm_ca, optimize = einsum_type)
    temp -= 1/2 * einsum('RPiab,iQxb,yxza,zy->RPQ', Y_KLCD, t1_xxae, t1_aaae, rdm_ca, optimize = einsum_type)
    temp -= 1/2 * einsum('RPiab,ixab,Qyxz,yz->RPQ', Y_KLCD, t1_xaee, t1_xaaa, rdm_ca, optimize = einsum_type)
    temp += 1/4 * einsum('RPiab,ixab,Qyzx,yz->RPQ', Y_KLCD, t1_xaee, t1_xaaa, rdm_ca, optimize = einsum_type)
    temp += 1/2 * einsum('RPiab,ixay,Qybz,xz->RPQ', Y_KLCD, t1_xaea, t1_xaea, rdm_ca, optimize = einsum_type)
    temp -= 1/4 * einsum('RPiab,ixay,Qyzb,xz->RPQ', Y_KLCD, t1_xaea, t1_xaae, rdm_ca, optimize = einsum_type)
    temp -= 1/2 * einsum('RPiab,ixay,Qzbx,yz->RPQ', Y_KLCD, t1_xaea, t1_xaea, rdm_ca, optimize = einsum_type)
    temp += 1/4 * einsum('RPiab,ixay,Qzxb,yz->RPQ', Y_KLCD, t1_xaea, t1_xaae, rdm_ca, optimize = einsum_type)
    temp += einsum('RPiab,ixba,Qyxz,yz->RPQ', Y_KLCD, t1_xaee, t1_xaaa, rdm_ca, optimize = einsum_type)
    temp -= 1/2 * einsum('RPiab,ixba,Qyzx,yz->RPQ', Y_KLCD, t1_xaee, t1_xaaa, rdm_ca, optimize = einsum_type)
    temp -= einsum('RPiab,ixby,Qyaz,xz->RPQ', Y_KLCD, t1_xaea, t1_xaea, rdm_ca, optimize = einsum_type)
    temp += 1/2 * einsum('RPiab,ixby,Qyza,xz->RPQ', Y_KLCD, t1_xaea, t1_xaae, rdm_ca, optimize = einsum_type)
    temp += einsum('RPiab,ixby,Qzax,yz->RPQ', Y_KLCD, t1_xaea, t1_xaea, rdm_ca, optimize = einsum_type)
    temp -= 1/2 * einsum('RPiab,ixby,Qzxa,yz->RPQ', Y_KLCD, t1_xaea, t1_xaae, rdm_ca, optimize = einsum_type)
    temp -= 1/4 * einsum('RPiab,ixya,Qybz,xz->RPQ', Y_KLCD, t1_xaae, t1_xaea, rdm_ca, optimize = einsum_type)
    temp += 1/2 * einsum('RPiab,ixya,Qyzb,xz->RPQ', Y_KLCD, t1_xaae, t1_xaae, rdm_ca, optimize = einsum_type)
    temp += 1/4 * einsum('RPiab,ixya,Qzbx,yz->RPQ', Y_KLCD, t1_xaae, t1_xaea, rdm_ca, optimize = einsum_type)
    temp -= 1/2 * einsum('RPiab,ixya,Qzxb,yz->RPQ', Y_KLCD, t1_xaae, t1_xaae, rdm_ca, optimize = einsum_type)
    temp += 1/2 * einsum('RPiab,ixyb,Qyaz,xz->RPQ', Y_KLCD, t1_xaae, t1_xaea, rdm_ca, optimize = einsum_type)
    temp -= 1/4 * einsum('RPiab,ixyb,Qyza,xz->RPQ', Y_KLCD, t1_xaae, t1_xaae, rdm_ca, optimize = einsum_type)
    temp -= 1/2 * einsum('RPiab,ixyb,Qzax,yz->RPQ', Y_KLCD, t1_xaae, t1_xaea, rdm_ca, optimize = einsum_type)
    temp += 1/4 * einsum('RPiab,ixyb,Qzxa,yz->RPQ', Y_KLCD, t1_xaae, t1_xaae, rdm_ca, optimize = einsum_type)
    temp -= einsum('RPiab,ixyz,Qyab,xz->RPQ', Y_KLCD, t1_xaaa, t1_xaee, rdm_ca, optimize = einsum_type)
    temp += 1/2 * einsum('RPiab,ixyz,Qyba,xz->RPQ', Y_KLCD, t1_xaaa, t1_xaee, rdm_ca, optimize = einsum_type)
    temp += 1/2 * einsum('RPiab,ixyz,Qzab,xy->RPQ', Y_KLCD, t1_xaaa, t1_xaee, rdm_ca, optimize = einsum_type)
    temp -= 1/4 * einsum('RPiab,ixyz,Qzba,xy->RPQ', Y_KLCD, t1_xaaa, t1_xaee, rdm_ca, optimize = einsum_type)
    TY[:, s_c:f_c, s_c:f_c] += temp

    temp = einsum('Rijab,iP,jQab->RPQ', Y_KLCD, t1_xa, t1_xaee, optimize = einsum_type)
    temp -= 2 * einsum('Rijab,iP,jQba->RPQ', Y_KLCD, t1_xa, t1_xaee, optimize = einsum_type)
    temp += einsum('Rijab,ijPa,Qb->RPQ', Y_KLCD, t1_xxae, t1_ae, optimize = einsum_type)
    temp -= 2 * einsum('Rijab,ijPx,Qxab->RPQ', Y_KLCD, t1_xxaa, t1_aaee, optimize = einsum_type)
    temp += einsum('Rijab,ijPx,Qxba->RPQ', Y_KLCD, t1_xxaa, t1_aaee, optimize = einsum_type)
    temp -= 2 * einsum('Rijab,jiPa,Qb->RPQ', Y_KLCD, t1_xxae, t1_ae, optimize = einsum_type)
    temp += einsum('Rijab,iQax,jxby,Py->RPQ', Y_KLCD, t1_xaea, t1_xaea, rdm_ca, optimize = einsum_type)
    temp -= 1/2 * einsum('Rijab,iQax,jxyb,Py->RPQ', Y_KLCD, t1_xaea, t1_xaae, rdm_ca, optimize = einsum_type)
    temp -= 1/2 * einsum('Rijab,iQbx,jxay,Py->RPQ', Y_KLCD, t1_xaea, t1_xaea, rdm_ca, optimize = einsum_type)
    temp += 1/4 * einsum('Rijab,iQbx,jxya,Py->RPQ', Y_KLCD, t1_xaea, t1_xaae, rdm_ca, optimize = einsum_type)
    temp -= 1/2 * einsum('Rijab,iQxa,jxby,Py->RPQ', Y_KLCD, t1_xaae, t1_xaea, rdm_ca, optimize = einsum_type)
    temp += 1/4 * einsum('Rijab,iQxa,jxyb,Py->RPQ', Y_KLCD, t1_xaae, t1_xaae, rdm_ca, optimize = einsum_type)
    temp += 1/4 * einsum('Rijab,iQxb,jxay,Py->RPQ', Y_KLCD, t1_xaae, t1_xaea, rdm_ca, optimize = einsum_type)
    temp -= 1/2 * einsum('Rijab,iQxb,jxya,Py->RPQ', Y_KLCD, t1_xaae, t1_xaae, rdm_ca, optimize = einsum_type)
    temp -= 1/2 * einsum('Rijab,iQxy,jxab,Py->RPQ', Y_KLCD, t1_xaaa, t1_xaee, rdm_ca, optimize = einsum_type)
    temp += einsum('Rijab,iQxy,jxba,Py->RPQ', Y_KLCD, t1_xaaa, t1_xaee, rdm_ca, optimize = einsum_type)
    temp += 1/4 * einsum('Rijab,iQxy,jyab,Px->RPQ', Y_KLCD, t1_xaaa, t1_xaee, rdm_ca, optimize = einsum_type)
    temp -= 1/2 * einsum('Rijab,iQxy,jyba,Px->RPQ', Y_KLCD, t1_xaaa, t1_xaee, rdm_ca, optimize = einsum_type)
    temp -= 1/2 * einsum('Rijab,ijPa,Qxyb,xy->RPQ', Y_KLCD, t1_xxae, t1_aaae, rdm_ca, optimize = einsum_type)
    temp += einsum('Rijab,ijPa,xQyb,xy->RPQ', Y_KLCD, t1_xxae, t1_aaae, rdm_ca, optimize = einsum_type)
    temp += einsum('Rijab,ijPx,Qyab,xy->RPQ', Y_KLCD, t1_xxaa, t1_aaee, rdm_ca, optimize = einsum_type)
    temp -= 1/2 * einsum('Rijab,ijPx,Qyba,xy->RPQ', Y_KLCD, t1_xxaa, t1_aaee, rdm_ca, optimize = einsum_type)
    temp -= 1/4 * einsum('Rijab,ijPx,xyab,Qy->RPQ', Y_KLCD, t1_xxaa, t1_aaee, rdm_ca, optimize = einsum_type)
    temp += 1/2 * einsum('Rijab,ijPx,yxab,Qy->RPQ', Y_KLCD, t1_xxaa, t1_aaee, rdm_ca, optimize = einsum_type)
    temp -= 1/4 * einsum('Rijab,ijxy,Qxab,Py->RPQ', Y_KLCD, t1_xxaa, t1_aaee, rdm_ca, optimize = einsum_type)
    temp += 1/2 * einsum('Rijab,ijxy,Qxba,Py->RPQ', Y_KLCD, t1_xxaa, t1_aaee, rdm_ca, optimize = einsum_type)
    temp += einsum('Rijab,ixPa,jQby,xy->RPQ', Y_KLCD, t1_xaae, t1_xaea, rdm_ca, optimize = einsum_type)
    temp -= 1/2 * einsum('Rijab,ixPa,jQyb,xy->RPQ', Y_KLCD, t1_xaae, t1_xaae, rdm_ca, optimize = einsum_type)
    temp -= 1/2 * einsum('Rijab,ixPa,jybx,Qy->RPQ', Y_KLCD, t1_xaae, t1_xaea, rdm_ca, optimize = einsum_type)
    temp += 1/4 * einsum('Rijab,ixPa,jyxb,Qy->RPQ', Y_KLCD, t1_xaae, t1_xaae, rdm_ca, optimize = einsum_type)
    temp -= 1/2 * einsum('Rijab,ixPb,jQay,xy->RPQ', Y_KLCD, t1_xaae, t1_xaea, rdm_ca, optimize = einsum_type)
    temp += einsum('Rijab,ixPb,jQya,xy->RPQ', Y_KLCD, t1_xaae, t1_xaae, rdm_ca, optimize = einsum_type)
    temp += 1/4 * einsum('Rijab,ixPb,jyax,Qy->RPQ', Y_KLCD, t1_xaae, t1_xaea, rdm_ca, optimize = einsum_type)
    temp -= 1/2 * einsum('Rijab,ixPb,jyxa,Qy->RPQ', Y_KLCD, t1_xaae, t1_xaae, rdm_ca, optimize = einsum_type)
    temp += einsum('Rijab,ixPy,jQab,yx->RPQ', Y_KLCD, t1_xaaa, t1_xaee, rdm_ca, optimize = einsum_type)
    temp -= 2 * einsum('Rijab,ixPy,jQba,yx->RPQ', Y_KLCD, t1_xaaa, t1_xaee, rdm_ca, optimize = einsum_type)
    temp -= 1/4 * einsum('Rijab,ixPy,jyab,Qx->RPQ', Y_KLCD, t1_xaaa, t1_xaee, rdm_ca, optimize = einsum_type)
    temp += 1/2 * einsum('Rijab,ixPy,jyba,Qx->RPQ', Y_KLCD, t1_xaaa, t1_xaee, rdm_ca, optimize = einsum_type)
    temp -= 2 * einsum('Rijab,ixaP,jQby,xy->RPQ', Y_KLCD, t1_xaea, t1_xaea, rdm_ca, optimize = einsum_type)
    temp += einsum('Rijab,ixaP,jQyb,xy->RPQ', Y_KLCD, t1_xaea, t1_xaae, rdm_ca, optimize = einsum_type)
    temp += einsum('Rijab,ixaP,jybx,Qy->RPQ', Y_KLCD, t1_xaea, t1_xaea, rdm_ca, optimize = einsum_type)
    temp -= 1/2 * einsum('Rijab,ixaP,jyxb,Qy->RPQ', Y_KLCD, t1_xaea, t1_xaae, rdm_ca, optimize = einsum_type)
    temp += einsum('Rijab,ixbP,jQay,xy->RPQ', Y_KLCD, t1_xaea, t1_xaea, rdm_ca, optimize = einsum_type)
    temp -= 1/2 * einsum('Rijab,ixbP,jQya,xy->RPQ', Y_KLCD, t1_xaea, t1_xaae, rdm_ca, optimize = einsum_type)
    temp -= 1/2 * einsum('Rijab,ixbP,jyax,Qy->RPQ', Y_KLCD, t1_xaea, t1_xaea, rdm_ca, optimize = einsum_type)
    temp += 1/4 * einsum('Rijab,ixbP,jyxa,Qy->RPQ', Y_KLCD, t1_xaea, t1_xaae, rdm_ca, optimize = einsum_type)
    temp -= 1/2 * einsum('Rijab,ixyP,jQab,yx->RPQ', Y_KLCD, t1_xaaa, t1_xaee, rdm_ca, optimize = einsum_type)
    temp += einsum('Rijab,ixyP,jQba,yx->RPQ', Y_KLCD, t1_xaaa, t1_xaee, rdm_ca, optimize = einsum_type)
    temp += 1/2 * einsum('Rijab,ixyP,jyab,Qx->RPQ', Y_KLCD, t1_xaaa, t1_xaee, rdm_ca, optimize = einsum_type)
    temp -= einsum('Rijab,ixyP,jyba,Qx->RPQ', Y_KLCD, t1_xaaa, t1_xaee, rdm_ca, optimize = einsum_type)
    temp += einsum('Rijab,jiPa,Qxyb,xy->RPQ', Y_KLCD, t1_xxae, t1_aaae, rdm_ca, optimize = einsum_type)
    temp -= 2 * einsum('Rijab,jiPa,xQyb,xy->RPQ', Y_KLCD, t1_xxae, t1_aaae, rdm_ca, optimize = einsum_type)
    temp -= einsum('Rijab,jixa,Qxyb,Py->RPQ', Y_KLCD, t1_xxae, t1_aaae, rdm_ca, optimize = einsum_type)
    temp += 1/2 * einsum('Rijab,jixa,xQyb,Py->RPQ', Y_KLCD, t1_xxae, t1_aaae, rdm_ca, optimize = einsum_type)
    temp -= 1/2 * einsum('Rijab,jixa,xyPb,Qy->RPQ', Y_KLCD, t1_xxae, t1_aaae, rdm_ca, optimize = einsum_type)
    temp += einsum('Rijab,jixa,yxPb,Qy->RPQ', Y_KLCD, t1_xxae, t1_aaae, rdm_ca, optimize = einsum_type)
    temp += 1/2 * einsum('Rijab,jixb,Qxya,Py->RPQ', Y_KLCD, t1_xxae, t1_aaae, rdm_ca, optimize = einsum_type)
    temp -= 1/4 * einsum('Rijab,jixb,xQya,Py->RPQ', Y_KLCD, t1_xxae, t1_aaae, rdm_ca, optimize = einsum_type)
    temp += 1/4 * einsum('Rijab,jixb,xyPa,Qy->RPQ', Y_KLCD, t1_xxae, t1_aaae, rdm_ca, optimize = einsum_type)
    temp -= 1/2 * einsum('Rijab,jixb,yxPa,Qy->RPQ', Y_KLCD, t1_xxae, t1_aaae, rdm_ca, optimize = einsum_type)
    TY[:, s_a:f_a, s_a:f_a] += temp

    temp = 1/2 * einsum('RijQa,ijxP,xa->RPQ', Y_KLCD, t1_xxae, t1_ae, optimize = einsum_type)
    temp += einsum('RijQa,ijxa,xP->RPQ', Y_KLCD, t1_xxae, t1_ae, optimize = einsum_type)
    temp += einsum('RijQa,ijxy,xyPa->RPQ', Y_KLCD, t1_xxaa, t1_aaee, optimize = einsum_type)
    temp -= 1/2 * einsum('RijQa,ijxy,yxPa->RPQ', Y_KLCD, t1_xxaa, t1_aaee, optimize = einsum_type)
    temp -= 1/2 * einsum('RijQa,ix,jxPa->RPQ', Y_KLCD, t1_xa, t1_xaee, optimize = einsum_type)
    temp += einsum('RijQa,ix,jxaP->RPQ', Y_KLCD, t1_xa, t1_xaee, optimize = einsum_type)
    temp += einsum('RijQa,ixPa,jx->RPQ', Y_KLCD, t1_xaee, t1_xa, optimize = einsum_type)
    temp -= 1/2 * einsum('RijQa,ixaP,jx->RPQ', Y_KLCD, t1_xaee, t1_xa, optimize = einsum_type)
    temp -= einsum('RijQa,jixP,xa->RPQ', Y_KLCD, t1_xxae, t1_ae, optimize = einsum_type)
    temp -= 1/2 * einsum('RijQa,jixa,xP->RPQ', Y_KLCD, t1_xxae, t1_ae, optimize = einsum_type)
    temp -= 1/4 * einsum('RijQa,ijxP,xyza,zy->RPQ', Y_KLCD, t1_xxae, t1_aaae, rdm_ca, optimize = einsum_type)
    temp += 1/2 * einsum('RijQa,ijxP,yxza,zy->RPQ', Y_KLCD, t1_xxae, t1_aaae, rdm_ca, optimize = einsum_type)
    temp -= 1/2 * einsum('RijQa,ijxa,xyzP,zy->RPQ', Y_KLCD, t1_xxae, t1_aaae, rdm_ca, optimize = einsum_type)
    temp += einsum('RijQa,ijxa,yxzP,zy->RPQ', Y_KLCD, t1_xxae, t1_aaae, rdm_ca, optimize = einsum_type)
    temp -= 1/2 * einsum('RijQa,ijxy,xzPa,yz->RPQ', Y_KLCD, t1_xxaa, t1_aaee, rdm_ca, optimize = einsum_type)
    temp += 1/4 * einsum('RijQa,ijxy,yzPa,xz->RPQ', Y_KLCD, t1_xxaa, t1_aaee, rdm_ca, optimize = einsum_type)
    temp += 1/4 * einsum('RijQa,ijxy,zxPa,yz->RPQ', Y_KLCD, t1_xxaa, t1_aaee, rdm_ca, optimize = einsum_type)
    temp -= 1/2 * einsum('RijQa,ijxy,zyPa,xz->RPQ', Y_KLCD, t1_xxaa, t1_aaee, rdm_ca, optimize = einsum_type)
    temp += einsum('RijQa,ixPa,jyxz,yz->RPQ', Y_KLCD, t1_xaee, t1_xaaa, rdm_ca, optimize = einsum_type)
    temp -= 1/2 * einsum('RijQa,ixPa,jyzx,yz->RPQ', Y_KLCD, t1_xaee, t1_xaaa, rdm_ca, optimize = einsum_type)
    temp -= einsum('RijQa,ixPy,jyaz,xz->RPQ', Y_KLCD, t1_xaea, t1_xaea, rdm_ca, optimize = einsum_type)
    temp += 1/2 * einsum('RijQa,ixPy,jyza,xz->RPQ', Y_KLCD, t1_xaea, t1_xaae, rdm_ca, optimize = einsum_type)
    temp += einsum('RijQa,ixPy,jzax,yz->RPQ', Y_KLCD, t1_xaea, t1_xaea, rdm_ca, optimize = einsum_type)
    temp -= 1/2 * einsum('RijQa,ixPy,jzxa,yz->RPQ', Y_KLCD, t1_xaea, t1_xaae, rdm_ca, optimize = einsum_type)
    temp -= 1/2 * einsum('RijQa,ixaP,jyxz,yz->RPQ', Y_KLCD, t1_xaee, t1_xaaa, rdm_ca, optimize = einsum_type)
    temp += 1/4 * einsum('RijQa,ixaP,jyzx,yz->RPQ', Y_KLCD, t1_xaee, t1_xaaa, rdm_ca, optimize = einsum_type)
    temp -= 1/2 * einsum('RijQa,ixay,jyPz,xz->RPQ', Y_KLCD, t1_xaea, t1_xaea, rdm_ca, optimize = einsum_type)
    temp += 1/4 * einsum('RijQa,ixay,jyzP,xz->RPQ', Y_KLCD, t1_xaea, t1_xaae, rdm_ca, optimize = einsum_type)
    temp += 1/2 * einsum('RijQa,ixay,jzPx,yz->RPQ', Y_KLCD, t1_xaea, t1_xaea, rdm_ca, optimize = einsum_type)
    temp -= 1/4 * einsum('RijQa,ixay,jzxP,yz->RPQ', Y_KLCD, t1_xaea, t1_xaae, rdm_ca, optimize = einsum_type)
    temp += 1/2 * einsum('RijQa,ixyP,jyaz,xz->RPQ', Y_KLCD, t1_xaae, t1_xaea, rdm_ca, optimize = einsum_type)
    temp -= 1/4 * einsum('RijQa,ixyP,jyza,xz->RPQ', Y_KLCD, t1_xaae, t1_xaae, rdm_ca, optimize = einsum_type)
    temp -= 1/2 * einsum('RijQa,ixyP,jzax,yz->RPQ', Y_KLCD, t1_xaae, t1_xaea, rdm_ca, optimize = einsum_type)
    temp += 1/4 * einsum('RijQa,ixyP,jzxa,yz->RPQ', Y_KLCD, t1_xaae, t1_xaae, rdm_ca, optimize = einsum_type)
    temp += 1/4 * einsum('RijQa,ixya,jyPz,xz->RPQ', Y_KLCD, t1_xaae, t1_xaea, rdm_ca, optimize = einsum_type)
    temp -= 1/2 * einsum('RijQa,ixya,jyzP,xz->RPQ', Y_KLCD, t1_xaae, t1_xaae, rdm_ca, optimize = einsum_type)
    temp -= 1/4 * einsum('RijQa,ixya,jzPx,yz->RPQ', Y_KLCD, t1_xaae, t1_xaea, rdm_ca, optimize = einsum_type)
    temp += 1/2 * einsum('RijQa,ixya,jzxP,yz->RPQ', Y_KLCD, t1_xaae, t1_xaae, rdm_ca, optimize = einsum_type)
    temp -= 1/2 * einsum('RijQa,ixyz,jyPa,xz->RPQ', Y_KLCD, t1_xaaa, t1_xaee, rdm_ca, optimize = einsum_type)
    temp += einsum('RijQa,ixyz,jyaP,xz->RPQ', Y_KLCD, t1_xaaa, t1_xaee, rdm_ca, optimize = einsum_type)
    temp += 1/4 * einsum('RijQa,ixyz,jzPa,xy->RPQ', Y_KLCD, t1_xaaa, t1_xaee, rdm_ca, optimize = einsum_type)
    temp -= 1/2 * einsum('RijQa,ixyz,jzaP,xy->RPQ', Y_KLCD, t1_xaaa, t1_xaee, rdm_ca, optimize = einsum_type)
    temp += 1/2 * einsum('RijQa,jixP,xyza,zy->RPQ', Y_KLCD, t1_xxae, t1_aaae, rdm_ca, optimize = einsum_type)
    temp -= einsum('RijQa,jixP,yxza,zy->RPQ', Y_KLCD, t1_xxae, t1_aaae, rdm_ca, optimize = einsum_type)
    temp += 1/4 * einsum('RijQa,jixa,xyzP,zy->RPQ', Y_KLCD, t1_xxae, t1_aaae, rdm_ca, optimize = einsum_type)
    temp -= 1/2 * einsum('RijQa,jixa,yxzP,zy->RPQ', Y_KLCD, t1_xxae, t1_aaae, rdm_ca, optimize = einsum_type)
    TY[:, s_e:f_e, s_e:f_e] += temp

    temp =- 1/2 * einsum('RPiab,Qixa,xb->RPQ', Y_KLCD, t1_vxae, t1_ae, optimize = einsum_type)
    temp += einsum('RPiab,Qixb,xa->RPQ', Y_KLCD, t1_vxae, t1_ae, optimize = einsum_type)
    temp += einsum('RPiab,Qixy,xyab->RPQ', Y_KLCD, t1_vxaa, t1_aaee, optimize = einsum_type)
    temp -= 1/2 * einsum('RPiab,Qixy,yxab->RPQ', Y_KLCD, t1_vxaa, t1_aaee, optimize = einsum_type)
    temp += einsum('RPiab,iQxa,xb->RPQ', Y_KLCD, t1_xvae, t1_ae, optimize = einsum_type)
    temp -= 1/2 * einsum('RPiab,iQxb,xa->RPQ', Y_KLCD, t1_xvae, t1_ae, optimize = einsum_type)
    temp -= einsum('RPiab,ix,Qxab->RPQ', Y_KLCD, t1_xa, t1_vaee, optimize = einsum_type)
    temp += 1/2 * einsum('RPiab,ix,Qxba->RPQ', Y_KLCD, t1_xa, t1_vaee, optimize = einsum_type)
    temp -= 1/2 * einsum('RPiab,ixab,Qx->RPQ', Y_KLCD, t1_xaee, t1_va, optimize = einsum_type)
    temp += einsum('RPiab,ixba,Qx->RPQ', Y_KLCD, t1_xaee, t1_va, optimize = einsum_type)
    temp += 1/4 * einsum('RPiab,Qixa,xyzb,zy->RPQ', Y_KLCD, t1_vxae, t1_aaae, rdm_ca, optimize = einsum_type)
    temp -= 1/2 * einsum('RPiab,Qixa,yxzb,zy->RPQ', Y_KLCD, t1_vxae, t1_aaae, rdm_ca, optimize = einsum_type)
    temp -= 1/2 * einsum('RPiab,Qixb,xyza,zy->RPQ', Y_KLCD, t1_vxae, t1_aaae, rdm_ca, optimize = einsum_type)
    temp += einsum('RPiab,Qixb,yxza,zy->RPQ', Y_KLCD, t1_vxae, t1_aaae, rdm_ca, optimize = einsum_type)
    temp -= 1/2 * einsum('RPiab,Qixy,xzab,yz->RPQ', Y_KLCD, t1_vxaa, t1_aaee, rdm_ca, optimize = einsum_type)
    temp += 1/4 * einsum('RPiab,Qixy,yzab,xz->RPQ', Y_KLCD, t1_vxaa, t1_aaee, rdm_ca, optimize = einsum_type)
    temp += 1/4 * einsum('RPiab,Qixy,zxab,yz->RPQ', Y_KLCD, t1_vxaa, t1_aaee, rdm_ca, optimize = einsum_type)
    temp -= 1/2 * einsum('RPiab,Qixy,zyab,xz->RPQ', Y_KLCD, t1_vxaa, t1_aaee, rdm_ca, optimize = einsum_type)
    temp -= 1/2 * einsum('RPiab,iQxa,xyzb,zy->RPQ', Y_KLCD, t1_xvae, t1_aaae, rdm_ca, optimize = einsum_type)
    temp += einsum('RPiab,iQxa,yxzb,zy->RPQ', Y_KLCD, t1_xvae, t1_aaae, rdm_ca, optimize = einsum_type)
    temp += 1/4 * einsum('RPiab,iQxb,xyza,zy->RPQ', Y_KLCD, t1_xvae, t1_aaae, rdm_ca, optimize = einsum_type)
    temp -= 1/2 * einsum('RPiab,iQxb,yxza,zy->RPQ', Y_KLCD, t1_xvae, t1_aaae, rdm_ca, optimize = einsum_type)
    temp -= 1/2 * einsum('RPiab,ixab,Qyxz,yz->RPQ', Y_KLCD, t1_xaee, t1_vaaa, rdm_ca, optimize = einsum_type)
    temp += 1/4 * einsum('RPiab,ixab,Qyzx,yz->RPQ', Y_KLCD, t1_xaee, t1_vaaa, rdm_ca, optimize = einsum_type)
    temp += 1/2 * einsum('RPiab,ixay,Qybz,xz->RPQ', Y_KLCD, t1_xaea, t1_vaea, rdm_ca, optimize = einsum_type)
    temp -= 1/4 * einsum('RPiab,ixay,Qyzb,xz->RPQ', Y_KLCD, t1_xaea, t1_vaae, rdm_ca, optimize = einsum_type)
    temp -= 1/2 * einsum('RPiab,ixay,Qzbx,yz->RPQ', Y_KLCD, t1_xaea, t1_vaea, rdm_ca, optimize = einsum_type)
    temp += 1/4 * einsum('RPiab,ixay,Qzxb,yz->RPQ', Y_KLCD, t1_xaea, t1_vaae, rdm_ca, optimize = einsum_type)
    temp += einsum('RPiab,ixba,Qyxz,yz->RPQ', Y_KLCD, t1_xaee, t1_vaaa, rdm_ca, optimize = einsum_type)
    temp -= 1/2 * einsum('RPiab,ixba,Qyzx,yz->RPQ', Y_KLCD, t1_xaee, t1_vaaa, rdm_ca, optimize = einsum_type)
    temp -= einsum('RPiab,ixby,Qyaz,xz->RPQ', Y_KLCD, t1_xaea, t1_vaea, rdm_ca, optimize = einsum_type)
    temp += 1/2 * einsum('RPiab,ixby,Qyza,xz->RPQ', Y_KLCD, t1_xaea, t1_vaae, rdm_ca, optimize = einsum_type)
    temp += einsum('RPiab,ixby,Qzax,yz->RPQ', Y_KLCD, t1_xaea, t1_vaea, rdm_ca, optimize = einsum_type)
    temp -= 1/2 * einsum('RPiab,ixby,Qzxa,yz->RPQ', Y_KLCD, t1_xaea, t1_vaae, rdm_ca, optimize = einsum_type)
    temp -= 1/4 * einsum('RPiab,ixya,Qybz,xz->RPQ', Y_KLCD, t1_xaae, t1_vaea, rdm_ca, optimize = einsum_type)
    temp += 1/2 * einsum('RPiab,ixya,Qyzb,xz->RPQ', Y_KLCD, t1_xaae, t1_vaae, rdm_ca, optimize = einsum_type)
    temp += 1/4 * einsum('RPiab,ixya,Qzbx,yz->RPQ', Y_KLCD, t1_xaae, t1_vaea, rdm_ca, optimize = einsum_type)
    temp -= 1/2 * einsum('RPiab,ixya,Qzxb,yz->RPQ', Y_KLCD, t1_xaae, t1_vaae, rdm_ca, optimize = einsum_type)
    temp += 1/2 * einsum('RPiab,ixyb,Qyaz,xz->RPQ', Y_KLCD, t1_xaae, t1_vaea, rdm_ca, optimize = einsum_type)
    temp -= 1/4 * einsum('RPiab,ixyb,Qyza,xz->RPQ', Y_KLCD, t1_xaae, t1_vaae, rdm_ca, optimize = einsum_type)
    temp -= 1/2 * einsum('RPiab,ixyb,Qzax,yz->RPQ', Y_KLCD, t1_xaae, t1_vaea, rdm_ca, optimize = einsum_type)
    temp += 1/4 * einsum('RPiab,ixyb,Qzxa,yz->RPQ', Y_KLCD, t1_xaae, t1_vaae, rdm_ca, optimize = einsum_type)
    temp -= einsum('RPiab,ixyz,Qyab,xz->RPQ', Y_KLCD, t1_xaaa, t1_vaee, rdm_ca, optimize = einsum_type)
    temp += 1/2 * einsum('RPiab,ixyz,Qyba,xz->RPQ', Y_KLCD, t1_xaaa, t1_vaee, rdm_ca, optimize = einsum_type)
    temp += 1/2 * einsum('RPiab,ixyz,Qzab,xy->RPQ', Y_KLCD, t1_xaaa, t1_vaee, rdm_ca, optimize = einsum_type)
    temp -= 1/4 * einsum('RPiab,ixyz,Qzba,xy->RPQ', Y_KLCD, t1_xaaa, t1_vaee, rdm_ca, optimize = einsum_type)
    TY[:, s_c:f_c, s_v:f_v] += temp

    temp =- 1/2 * einsum('RPiab,iQax,xb->RPQ', Y_KLCD, t1_xaea, t1_ae, optimize = einsum_type)
    temp += einsum('RPiab,iQbx,xa->RPQ', Y_KLCD, t1_xaea, t1_ae, optimize = einsum_type)
    temp += einsum('RPiab,iQxa,xb->RPQ', Y_KLCD, t1_xaae, t1_ae, optimize = einsum_type)
    temp -= 1/2 * einsum('RPiab,iQxb,xa->RPQ', Y_KLCD, t1_xaae, t1_ae, optimize = einsum_type)
    temp -= 1/2 * einsum('RPiab,iQxy,xyab->RPQ', Y_KLCD, t1_xaaa, t1_aaee, optimize = einsum_type)
    temp += einsum('RPiab,iQxy,yxab->RPQ', Y_KLCD, t1_xaaa, t1_aaee, optimize = einsum_type)
    temp += 1/2 * einsum('RPiab,ijab,jQ->RPQ', Y_KLCD, t1_xxee, t1_xa, optimize = einsum_type)
    temp -= einsum('RPiab,ijba,jQ->RPQ', Y_KLCD, t1_xxee, t1_xa, optimize = einsum_type)
    temp += 1/2 * einsum('RPiab,ijab,jQ->RPQ', Y_KLCD, t1_xvee, t1_va, optimize = einsum_type)
    temp -= einsum('RPiab,ijba,jQ->RPQ', Y_KLCD, t1_xvee, t1_va, optimize = einsum_type)
    temp -= einsum('RPiab,ix,Qxab->RPQ', Y_KLCD, t1_xa, t1_aaee, optimize = einsum_type)
    temp += 1/2 * einsum('RPiab,ix,Qxba->RPQ', Y_KLCD, t1_xa, t1_aaee, optimize = einsum_type)
    temp += einsum('Rijab,PiQx,jxab->RPQ', Y_KLCD, t1_xxaa, t1_xaee, optimize = einsum_type)
    temp -= 2 * einsum('Rijab,PiQx,jxba->RPQ', Y_KLCD, t1_xxaa, t1_xaee, optimize = einsum_type)
    temp += einsum('Rijab,Piab,jQ->RPQ', Y_KLCD, t1_xxee, t1_xa, optimize = einsum_type)
    temp -= 2 * einsum('Rijab,Piba,jQ->RPQ', Y_KLCD, t1_xxee, t1_xa, optimize = einsum_type)
    temp -= 1/2 * einsum('Rijab,PixQ,jxab->RPQ', Y_KLCD, t1_xxaa, t1_xaee, optimize = einsum_type)
    temp += einsum('Rijab,PixQ,jxba->RPQ', Y_KLCD, t1_xxaa, t1_xaee, optimize = einsum_type)
    temp -= einsum('Rijab,Pixa,jxQb->RPQ', Y_KLCD, t1_xxae, t1_xaae, optimize = einsum_type)
    temp += 2 * einsum('Rijab,Pixa,jxbQ->RPQ', Y_KLCD, t1_xxae, t1_xaea, optimize = einsum_type)
    temp += 1/2 * einsum('Rijab,Pixb,jxQa->RPQ', Y_KLCD, t1_xxae, t1_xaae, optimize = einsum_type)
    temp -= einsum('Rijab,Pixb,jxaQ->RPQ', Y_KLCD, t1_xxae, t1_xaea, optimize = einsum_type)
    temp += 1/2 * einsum('Rijab,iPxa,jxQb->RPQ', Y_KLCD, t1_xxae, t1_xaae, optimize = einsum_type)
    temp -= einsum('Rijab,iPxa,jxbQ->RPQ', Y_KLCD, t1_xxae, t1_xaea, optimize = einsum_type)
    temp -= einsum('Rijab,iPxb,jxQa->RPQ', Y_KLCD, t1_xxae, t1_xaae, optimize = einsum_type)
    temp += 1/2 * einsum('Rijab,iPxb,jxaQ->RPQ', Y_KLCD, t1_xxae, t1_xaea, optimize = einsum_type)
    temp += einsum('Rijab,ijQa,Pb->RPQ', Y_KLCD, t1_xxae, t1_xe, optimize = einsum_type)
    temp -= einsum('Rijab,ijQx,Pxab->RPQ', Y_KLCD, t1_xxaa, t1_xaee, optimize = einsum_type)
    temp += 1/2 * einsum('Rijab,ijQx,Pxba->RPQ', Y_KLCD, t1_xxaa, t1_xaee, optimize = einsum_type)
    temp -= 2 * einsum('Rijab,jiQa,Pb->RPQ', Y_KLCD, t1_xxae, t1_xe, optimize = einsum_type)
    temp += 2 * einsum('Rijab,jixa,PxQb->RPQ', Y_KLCD, t1_xxae, t1_xaae, optimize = einsum_type)
    temp -= einsum('Rijab,jixa,PxbQ->RPQ', Y_KLCD, t1_xxae, t1_xaea, optimize = einsum_type)
    temp -= einsum('Rijab,jixb,PxQa->RPQ', Y_KLCD, t1_xxae, t1_xaae, optimize = einsum_type)
    temp += 1/2 * einsum('Rijab,jixb,PxaQ->RPQ', Y_KLCD, t1_xxae, t1_xaea, optimize = einsum_type)
    temp += 1/4 * einsum('RPiab,iQax,xyzb,zy->RPQ', Y_KLCD, t1_xaea, t1_aaae, rdm_ca, optimize = einsum_type)
    temp -= 1/2 * einsum('RPiab,iQax,yxzb,zy->RPQ', Y_KLCD, t1_xaea, t1_aaae, rdm_ca, optimize = einsum_type)
    temp -= 1/2 * einsum('RPiab,iQbx,xyza,zy->RPQ', Y_KLCD, t1_xaea, t1_aaae, rdm_ca, optimize = einsum_type)
    temp += einsum('RPiab,iQbx,yxza,zy->RPQ', Y_KLCD, t1_xaea, t1_aaae, rdm_ca, optimize = einsum_type)
    temp -= 1/2 * einsum('RPiab,iQxa,xyzb,zy->RPQ', Y_KLCD, t1_xaae, t1_aaae, rdm_ca, optimize = einsum_type)
    temp += einsum('RPiab,iQxa,yxzb,zy->RPQ', Y_KLCD, t1_xaae, t1_aaae, rdm_ca, optimize = einsum_type)
    temp += 1/4 * einsum('RPiab,iQxb,xyza,zy->RPQ', Y_KLCD, t1_xaae, t1_aaae, rdm_ca, optimize = einsum_type)
    temp -= 1/2 * einsum('RPiab,iQxb,yxza,zy->RPQ', Y_KLCD, t1_xaae, t1_aaae, rdm_ca, optimize = einsum_type)
    temp += 1/4 * einsum('RPiab,iQxy,xzab,yz->RPQ', Y_KLCD, t1_xaaa, t1_aaee, rdm_ca, optimize = einsum_type)
    temp -= 1/2 * einsum('RPiab,iQxy,yzab,xz->RPQ', Y_KLCD, t1_xaaa, t1_aaee, rdm_ca, optimize = einsum_type)
    temp -= 1/2 * einsum('RPiab,iQxy,zxab,yz->RPQ', Y_KLCD, t1_xaaa, t1_aaee, rdm_ca, optimize = einsum_type)
    temp += 1/4 * einsum('RPiab,iQxy,zyab,xz->RPQ', Y_KLCD, t1_xaaa, t1_aaee, rdm_ca, optimize = einsum_type)
    temp += 1/2 * einsum('RPiab,ijab,jxQy,yx->RPQ', Y_KLCD, t1_xxee, t1_xaaa, rdm_ca, optimize = einsum_type)
    temp -= 1/4 * einsum('RPiab,ijab,jxyQ,yx->RPQ', Y_KLCD, t1_xxee, t1_xaaa, rdm_ca, optimize = einsum_type)
    temp -= einsum('RPiab,ijba,jxQy,yx->RPQ', Y_KLCD, t1_xxee, t1_xaaa, rdm_ca, optimize = einsum_type)
    temp += 1/2 * einsum('RPiab,ijba,jxyQ,yx->RPQ', Y_KLCD, t1_xxee, t1_xaaa, rdm_ca, optimize = einsum_type)
    temp += 1/2 * einsum('RPiab,ijab,jxQy,yx->RPQ', Y_KLCD, t1_xvee, t1_vaaa, rdm_ca, optimize = einsum_type)
    temp -= 1/4 * einsum('RPiab,ijab,jxyQ,yx->RPQ', Y_KLCD, t1_xvee, t1_vaaa, rdm_ca, optimize = einsum_type)
    temp -= einsum('RPiab,ijba,jxQy,yx->RPQ', Y_KLCD, t1_xvee, t1_vaaa, rdm_ca, optimize = einsum_type)
    temp += 1/2 * einsum('RPiab,ijba,jxyQ,yx->RPQ', Y_KLCD, t1_xvee, t1_vaaa, rdm_ca, optimize = einsum_type)
    temp -= 1/4 * einsum('RPiab,ixay,Qyzb,xz->RPQ', Y_KLCD, t1_xaea, t1_aaae, rdm_ca, optimize = einsum_type)
    temp += 1/4 * einsum('RPiab,ixay,Qzxb,yz->RPQ', Y_KLCD, t1_xaea, t1_aaae, rdm_ca, optimize = einsum_type)
    temp += 1/2 * einsum('RPiab,ixay,yQzb,xz->RPQ', Y_KLCD, t1_xaea, t1_aaae, rdm_ca, optimize = einsum_type)
    temp -= 1/2 * einsum('RPiab,ixay,zQxb,yz->RPQ', Y_KLCD, t1_xaea, t1_aaae, rdm_ca, optimize = einsum_type)
    temp += 1/2 * einsum('RPiab,ixby,Qyza,xz->RPQ', Y_KLCD, t1_xaea, t1_aaae, rdm_ca, optimize = einsum_type)
    temp -= 1/2 * einsum('RPiab,ixby,Qzxa,yz->RPQ', Y_KLCD, t1_xaea, t1_aaae, rdm_ca, optimize = einsum_type)
    temp -= einsum('RPiab,ixby,yQza,xz->RPQ', Y_KLCD, t1_xaea, t1_aaae, rdm_ca, optimize = einsum_type)
    temp += einsum('RPiab,ixby,zQxa,yz->RPQ', Y_KLCD, t1_xaea, t1_aaae, rdm_ca, optimize = einsum_type)
    temp += 1/2 * einsum('RPiab,ixya,Qyzb,xz->RPQ', Y_KLCD, t1_xaae, t1_aaae, rdm_ca, optimize = einsum_type)
    temp -= 1/2 * einsum('RPiab,ixya,Qzxb,yz->RPQ', Y_KLCD, t1_xaae, t1_aaae, rdm_ca, optimize = einsum_type)
    temp -= 1/4 * einsum('RPiab,ixya,yQzb,xz->RPQ', Y_KLCD, t1_xaae, t1_aaae, rdm_ca, optimize = einsum_type)
    temp += 1/4 * einsum('RPiab,ixya,zQxb,yz->RPQ', Y_KLCD, t1_xaae, t1_aaae, rdm_ca, optimize = einsum_type)
    temp -= 1/4 * einsum('RPiab,ixyb,Qyza,xz->RPQ', Y_KLCD, t1_xaae, t1_aaae, rdm_ca, optimize = einsum_type)
    temp += 1/4 * einsum('RPiab,ixyb,Qzxa,yz->RPQ', Y_KLCD, t1_xaae, t1_aaae, rdm_ca, optimize = einsum_type)
    temp += 1/2 * einsum('RPiab,ixyb,yQza,xz->RPQ', Y_KLCD, t1_xaae, t1_aaae, rdm_ca, optimize = einsum_type)
    temp -= 1/2 * einsum('RPiab,ixyb,zQxa,yz->RPQ', Y_KLCD, t1_xaae, t1_aaae, rdm_ca, optimize = einsum_type)
    temp -= einsum('RPiab,ixyz,Qyab,xz->RPQ', Y_KLCD, t1_xaaa, t1_aaee, rdm_ca, optimize = einsum_type)
    temp += 1/2 * einsum('RPiab,ixyz,Qyba,xz->RPQ', Y_KLCD, t1_xaaa, t1_aaee, rdm_ca, optimize = einsum_type)
    temp += 1/2 * einsum('RPiab,ixyz,Qzab,xy->RPQ', Y_KLCD, t1_xaaa, t1_aaee, rdm_ca, optimize = einsum_type)
    temp -= 1/4 * einsum('RPiab,ixyz,Qzba,xy->RPQ', Y_KLCD, t1_xaaa, t1_aaee, rdm_ca, optimize = einsum_type)
    temp += einsum('Rijab,Piab,jxQy,yx->RPQ', Y_KLCD, t1_xxee, t1_xaaa, rdm_ca, optimize = einsum_type)
    temp -= 1/2 * einsum('Rijab,Piab,jxyQ,yx->RPQ', Y_KLCD, t1_xxee, t1_xaaa, rdm_ca, optimize = einsum_type)
    temp -= 2 * einsum('Rijab,Piba,jxQy,yx->RPQ', Y_KLCD, t1_xxee, t1_xaaa, rdm_ca, optimize = einsum_type)
    temp += einsum('Rijab,Piba,jxyQ,yx->RPQ', Y_KLCD, t1_xxee, t1_xaaa, rdm_ca, optimize = einsum_type)
    temp += einsum('Rijab,Pixa,jxby,Qy->RPQ', Y_KLCD, t1_xxae, t1_xaea, rdm_ca, optimize = einsum_type)
    temp -= 1/2 * einsum('Rijab,Pixa,jxyb,Qy->RPQ', Y_KLCD, t1_xxae, t1_xaae, rdm_ca, optimize = einsum_type)
    temp += einsum('Rijab,Pixa,jyQb,xy->RPQ', Y_KLCD, t1_xxae, t1_xaae, rdm_ca, optimize = einsum_type)
    temp -= 2 * einsum('Rijab,Pixa,jybQ,xy->RPQ', Y_KLCD, t1_xxae, t1_xaea, rdm_ca, optimize = einsum_type)
    temp -= 1/2 * einsum('Rijab,Pixb,jxay,Qy->RPQ', Y_KLCD, t1_xxae, t1_xaea, rdm_ca, optimize = einsum_type)
    temp += 1/4 * einsum('Rijab,Pixb,jxya,Qy->RPQ', Y_KLCD, t1_xxae, t1_xaae, rdm_ca, optimize = einsum_type)
    temp -= 1/2 * einsum('Rijab,Pixb,jyQa,xy->RPQ', Y_KLCD, t1_xxae, t1_xaae, rdm_ca, optimize = einsum_type)
    temp += einsum('Rijab,Pixb,jyaQ,xy->RPQ', Y_KLCD, t1_xxae, t1_xaea, rdm_ca, optimize = einsum_type)
    temp += 1/4 * einsum('Rijab,Pixy,jxab,Qy->RPQ', Y_KLCD, t1_xxaa, t1_xaee, rdm_ca, optimize = einsum_type)
    temp -= 1/2 * einsum('Rijab,Pixy,jxba,Qy->RPQ', Y_KLCD, t1_xxaa, t1_xaee, rdm_ca, optimize = einsum_type)
    temp -= 1/2 * einsum('Rijab,Pixy,jyab,Qx->RPQ', Y_KLCD, t1_xxaa, t1_xaee, rdm_ca, optimize = einsum_type)
    temp += einsum('Rijab,Pixy,jyba,Qx->RPQ', Y_KLCD, t1_xxaa, t1_xaee, rdm_ca, optimize = einsum_type)
    temp -= 1/2 * einsum('Rijab,iPxa,jxby,Qy->RPQ', Y_KLCD, t1_xxae, t1_xaea, rdm_ca, optimize = einsum_type)
    temp += 1/4 * einsum('Rijab,iPxa,jxyb,Qy->RPQ', Y_KLCD, t1_xxae, t1_xaae, rdm_ca, optimize = einsum_type)
    temp -= 1/2 * einsum('Rijab,iPxa,jyQb,xy->RPQ', Y_KLCD, t1_xxae, t1_xaae, rdm_ca, optimize = einsum_type)
    temp += einsum('Rijab,iPxa,jybQ,xy->RPQ', Y_KLCD, t1_xxae, t1_xaea, rdm_ca, optimize = einsum_type)
    temp += 1/4 * einsum('Rijab,iPxb,jxay,Qy->RPQ', Y_KLCD, t1_xxae, t1_xaea, rdm_ca, optimize = einsum_type)
    temp -= 1/2 * einsum('Rijab,iPxb,jxya,Qy->RPQ', Y_KLCD, t1_xxae, t1_xaae, rdm_ca, optimize = einsum_type)
    temp += einsum('Rijab,iPxb,jyQa,xy->RPQ', Y_KLCD, t1_xxae, t1_xaae, rdm_ca, optimize = einsum_type)
    temp -= 1/2 * einsum('Rijab,iPxb,jyaQ,xy->RPQ', Y_KLCD, t1_xxae, t1_xaea, rdm_ca, optimize = einsum_type)
    temp += einsum('Rijab,ijQa,Pxby,xy->RPQ', Y_KLCD, t1_xxae, t1_xaea, rdm_ca, optimize = einsum_type)
    temp -= 1/2 * einsum('Rijab,ijQa,Pxyb,xy->RPQ', Y_KLCD, t1_xxae, t1_xaae, rdm_ca, optimize = einsum_type)
    temp += einsum('Rijab,ijQx,Pyab,xy->RPQ', Y_KLCD, t1_xxaa, t1_xaee, rdm_ca, optimize = einsum_type)
    temp -= 1/2 * einsum('Rijab,ijQx,Pyba,xy->RPQ', Y_KLCD, t1_xxaa, t1_xaee, rdm_ca, optimize = einsum_type)
    temp -= 1/4 * einsum('Rijab,ijxy,Pxab,Qy->RPQ', Y_KLCD, t1_xxaa, t1_xaee, rdm_ca, optimize = einsum_type)
    temp += 1/2 * einsum('Rijab,ijxy,Pxba,Qy->RPQ', Y_KLCD, t1_xxaa, t1_xaee, rdm_ca, optimize = einsum_type)
    temp -= 2 * einsum('Rijab,jiQa,Pxby,xy->RPQ', Y_KLCD, t1_xxae, t1_xaea, rdm_ca, optimize = einsum_type)
    temp += einsum('Rijab,jiQa,Pxyb,xy->RPQ', Y_KLCD, t1_xxae, t1_xaae, rdm_ca, optimize = einsum_type)
    temp += 1/2 * einsum('Rijab,jixa,Pxby,Qy->RPQ', Y_KLCD, t1_xxae, t1_xaea, rdm_ca, optimize = einsum_type)
    temp -= einsum('Rijab,jixa,Pxyb,Qy->RPQ', Y_KLCD, t1_xxae, t1_xaae, rdm_ca, optimize = einsum_type)
    temp -= 1/4 * einsum('Rijab,jixb,Pxay,Qy->RPQ', Y_KLCD, t1_xxae, t1_xaea, rdm_ca, optimize = einsum_type)
    temp += 1/2 * einsum('Rijab,jixb,Pxya,Qy->RPQ', Y_KLCD, t1_xxae, t1_xaae, rdm_ca, optimize = einsum_type)
    TY[:, s_c:f_c, s_a:f_a] += temp

    temp = einsum('Rijab,PiQx,jxab->RPQ', Y_KLCD, t1_vxaa, t1_xaee, optimize = einsum_type)
    temp -= 2 * einsum('Rijab,PiQx,jxba->RPQ', Y_KLCD, t1_vxaa, t1_xaee, optimize = einsum_type)
    temp += einsum('Rijab,Piab,jQ->RPQ', Y_KLCD, t1_vxee, t1_xa, optimize = einsum_type)
    temp -= 2 * einsum('Rijab,Piba,jQ->RPQ', Y_KLCD, t1_vxee, t1_xa, optimize = einsum_type)
    temp -= 1/2 * einsum('Rijab,PixQ,jxab->RPQ', Y_KLCD, t1_vxaa, t1_xaee, optimize = einsum_type)
    temp += einsum('Rijab,PixQ,jxba->RPQ', Y_KLCD, t1_vxaa, t1_xaee, optimize = einsum_type)
    temp -= einsum('Rijab,Pixa,jxQb->RPQ', Y_KLCD, t1_vxae, t1_xaae, optimize = einsum_type)
    temp += 2 * einsum('Rijab,Pixa,jxbQ->RPQ', Y_KLCD, t1_vxae, t1_xaea, optimize = einsum_type)
    temp += 1/2 * einsum('Rijab,Pixb,jxQa->RPQ', Y_KLCD, t1_vxae, t1_xaae, optimize = einsum_type)
    temp -= einsum('Rijab,Pixb,jxaQ->RPQ', Y_KLCD, t1_vxae, t1_xaea, optimize = einsum_type)
    temp += 1/2 * einsum('Rijab,iPxa,jxQb->RPQ', Y_KLCD, t1_xvae, t1_xaae, optimize = einsum_type)
    temp -= einsum('Rijab,iPxa,jxbQ->RPQ', Y_KLCD, t1_xvae, t1_xaea, optimize = einsum_type)
    temp -= einsum('Rijab,iPxb,jxQa->RPQ', Y_KLCD, t1_xvae, t1_xaae, optimize = einsum_type)
    temp += 1/2 * einsum('Rijab,iPxb,jxaQ->RPQ', Y_KLCD, t1_xvae, t1_xaea, optimize = einsum_type)
    temp += einsum('Rijab,ijQa,Pb->RPQ', Y_KLCD, t1_xxae, t1_ve, optimize = einsum_type)
    temp -= einsum('Rijab,ijQx,Pxab->RPQ', Y_KLCD, t1_xxaa, t1_vaee, optimize = einsum_type)
    temp += 1/2 * einsum('Rijab,ijQx,Pxba->RPQ', Y_KLCD, t1_xxaa, t1_vaee, optimize = einsum_type)
    temp -= 2 * einsum('Rijab,jiQa,Pb->RPQ', Y_KLCD, t1_xxae, t1_ve, optimize = einsum_type)
    temp += 2 * einsum('Rijab,jixa,PxQb->RPQ', Y_KLCD, t1_xxae, t1_vaae, optimize = einsum_type)
    temp -= einsum('Rijab,jixa,PxbQ->RPQ', Y_KLCD, t1_xxae, t1_vaea, optimize = einsum_type)
    temp -= einsum('Rijab,jixb,PxQa->RPQ', Y_KLCD, t1_xxae, t1_vaae, optimize = einsum_type)
    temp += 1/2 * einsum('Rijab,jixb,PxaQ->RPQ', Y_KLCD, t1_xxae, t1_vaea, optimize = einsum_type)
    temp += einsum('Rijab,Piab,jxQy,yx->RPQ', Y_KLCD, t1_vxee, t1_xaaa, rdm_ca, optimize = einsum_type)
    temp -= 1/2 * einsum('Rijab,Piab,jxyQ,yx->RPQ', Y_KLCD, t1_vxee, t1_xaaa, rdm_ca, optimize = einsum_type)
    temp -= 2 * einsum('Rijab,Piba,jxQy,yx->RPQ', Y_KLCD, t1_vxee, t1_xaaa, rdm_ca, optimize = einsum_type)
    temp += einsum('Rijab,Piba,jxyQ,yx->RPQ', Y_KLCD, t1_vxee, t1_xaaa, rdm_ca, optimize = einsum_type)
    temp += einsum('Rijab,Pixa,jxby,Qy->RPQ', Y_KLCD, t1_vxae, t1_xaea, rdm_ca, optimize = einsum_type)
    temp -= 1/2 * einsum('Rijab,Pixa,jxyb,Qy->RPQ', Y_KLCD, t1_vxae, t1_xaae, rdm_ca, optimize = einsum_type)
    temp += einsum('Rijab,Pixa,jyQb,xy->RPQ', Y_KLCD, t1_vxae, t1_xaae, rdm_ca, optimize = einsum_type)
    temp -= 2 * einsum('Rijab,Pixa,jybQ,xy->RPQ', Y_KLCD, t1_vxae, t1_xaea, rdm_ca, optimize = einsum_type)
    temp -= 1/2 * einsum('Rijab,Pixb,jxay,Qy->RPQ', Y_KLCD, t1_vxae, t1_xaea, rdm_ca, optimize = einsum_type)
    temp += 1/4 * einsum('Rijab,Pixb,jxya,Qy->RPQ', Y_KLCD, t1_vxae, t1_xaae, rdm_ca, optimize = einsum_type)
    temp -= 1/2 * einsum('Rijab,Pixb,jyQa,xy->RPQ', Y_KLCD, t1_vxae, t1_xaae, rdm_ca, optimize = einsum_type)
    temp += einsum('Rijab,Pixb,jyaQ,xy->RPQ', Y_KLCD, t1_vxae, t1_xaea, rdm_ca, optimize = einsum_type)
    temp += 1/4 * einsum('Rijab,Pixy,jxab,Qy->RPQ', Y_KLCD, t1_vxaa, t1_xaee, rdm_ca, optimize = einsum_type)
    temp -= 1/2 * einsum('Rijab,Pixy,jxba,Qy->RPQ', Y_KLCD, t1_vxaa, t1_xaee, rdm_ca, optimize = einsum_type)
    temp -= 1/2 * einsum('Rijab,Pixy,jyab,Qx->RPQ', Y_KLCD, t1_vxaa, t1_xaee, rdm_ca, optimize = einsum_type)
    temp += einsum('Rijab,Pixy,jyba,Qx->RPQ', Y_KLCD, t1_vxaa, t1_xaee, rdm_ca, optimize = einsum_type)
    temp -= 1/2 * einsum('Rijab,iPxa,jxby,Qy->RPQ', Y_KLCD, t1_xvae, t1_xaea, rdm_ca, optimize = einsum_type)
    temp += 1/4 * einsum('Rijab,iPxa,jxyb,Qy->RPQ', Y_KLCD, t1_xvae, t1_xaae, rdm_ca, optimize = einsum_type)
    temp -= 1/2 * einsum('Rijab,iPxa,jyQb,xy->RPQ', Y_KLCD, t1_xvae, t1_xaae, rdm_ca, optimize = einsum_type)
    temp += einsum('Rijab,iPxa,jybQ,xy->RPQ', Y_KLCD, t1_xvae, t1_xaea, rdm_ca, optimize = einsum_type)
    temp += 1/4 * einsum('Rijab,iPxb,jxay,Qy->RPQ', Y_KLCD, t1_xvae, t1_xaea, rdm_ca, optimize = einsum_type)
    temp -= 1/2 * einsum('Rijab,iPxb,jxya,Qy->RPQ', Y_KLCD, t1_xvae, t1_xaae, rdm_ca, optimize = einsum_type)
    temp += einsum('Rijab,iPxb,jyQa,xy->RPQ', Y_KLCD, t1_xvae, t1_xaae, rdm_ca, optimize = einsum_type)
    temp -= 1/2 * einsum('Rijab,iPxb,jyaQ,xy->RPQ', Y_KLCD, t1_xvae, t1_xaea, rdm_ca, optimize = einsum_type)
    temp += einsum('Rijab,ijQa,Pxby,xy->RPQ', Y_KLCD, t1_xxae, t1_vaea, rdm_ca, optimize = einsum_type)
    temp -= 1/2 * einsum('Rijab,ijQa,Pxyb,xy->RPQ', Y_KLCD, t1_xxae, t1_vaae, rdm_ca, optimize = einsum_type)
    temp += einsum('Rijab,ijQx,Pyab,xy->RPQ', Y_KLCD, t1_xxaa, t1_vaee, rdm_ca, optimize = einsum_type)
    temp -= 1/2 * einsum('Rijab,ijQx,Pyba,xy->RPQ', Y_KLCD, t1_xxaa, t1_vaee, rdm_ca, optimize = einsum_type)
    temp -= 1/4 * einsum('Rijab,ijxy,Pxab,Qy->RPQ', Y_KLCD, t1_xxaa, t1_vaee, rdm_ca, optimize = einsum_type)
    temp += 1/2 * einsum('Rijab,ijxy,Pxba,Qy->RPQ', Y_KLCD, t1_xxaa, t1_vaee, rdm_ca, optimize = einsum_type)
    temp -= 2 * einsum('Rijab,jiQa,Pxby,xy->RPQ', Y_KLCD, t1_xxae, t1_vaea, rdm_ca, optimize = einsum_type)
    temp += einsum('Rijab,jiQa,Pxyb,xy->RPQ', Y_KLCD, t1_xxae, t1_vaae, rdm_ca, optimize = einsum_type)
    temp += 1/2 * einsum('Rijab,jixa,Pxby,Qy->RPQ', Y_KLCD, t1_xxae, t1_vaea, rdm_ca, optimize = einsum_type)
    temp -= einsum('Rijab,jixa,Pxyb,Qy->RPQ', Y_KLCD, t1_xxae, t1_vaae, rdm_ca, optimize = einsum_type)
    temp -= 1/4 * einsum('Rijab,jixb,Pxay,Qy->RPQ', Y_KLCD, t1_xxae, t1_vaea, rdm_ca, optimize = einsum_type)
    temp += 1/2 * einsum('Rijab,jixb,Pxya,Qy->RPQ', Y_KLCD, t1_xxae, t1_vaae, rdm_ca, optimize = einsum_type)
    TY[:, s_v:f_v, s_a:f_a] += temp

    temp = 1/2 * einsum('RPiab,ijab,jQ->RPQ', Y_KLCD, t1_xxee, t1_xe, optimize = einsum_type)
    temp -= einsum('RPiab,ijba,jQ->RPQ', Y_KLCD, t1_xxee, t1_xe, optimize = einsum_type)
    temp += 1/2 * einsum('RPiab,ijab,jQ->RPQ', Y_KLCD, t1_xvee, t1_ve, optimize = einsum_type)
    temp -= einsum('RPiab,ijba,jQ->RPQ', Y_KLCD, t1_xvee, t1_ve, optimize = einsum_type)
    temp += 1/2 * einsum('RPiab,ixab,xQ->RPQ', Y_KLCD, t1_xaee, t1_ae, optimize = einsum_type)
    temp -= einsum('RPiab,ixba,xQ->RPQ', Y_KLCD, t1_xaee, t1_ae, optimize = einsum_type)
    temp += 1/2 * einsum('RijQa,ijab,Pb->RPQ', Y_KLCD, t1_xxee, t1_xe, optimize = einsum_type)
    temp -= einsum('RijQa,ijba,Pb->RPQ', Y_KLCD, t1_xxee, t1_xe, optimize = einsum_type)
    temp -= einsum('RijQa,ijxa,Px->RPQ', Y_KLCD, t1_xxae, t1_xa, optimize = einsum_type)
    temp += 1/2 * einsum('RijQa,jixa,Px->RPQ', Y_KLCD, t1_xxae, t1_xa, optimize = einsum_type)
    temp += einsum('Rijab,Piab,jQ->RPQ', Y_KLCD, t1_xxee, t1_xe, optimize = einsum_type)
    temp -= 2 * einsum('Rijab,Piba,jQ->RPQ', Y_KLCD, t1_xxee, t1_xe, optimize = einsum_type)
    temp -= 1/2 * einsum('Rijab,PixQ,jxab->RPQ', Y_KLCD, t1_xxae, t1_xaee, optimize = einsum_type)
    temp += einsum('Rijab,PixQ,jxba->RPQ', Y_KLCD, t1_xxae, t1_xaee, optimize = einsum_type)
    temp -= einsum('Rijab,Pixa,jxQb->RPQ', Y_KLCD, t1_xxae, t1_xaee, optimize = einsum_type)
    temp += 2 * einsum('Rijab,Pixa,jxbQ->RPQ', Y_KLCD, t1_xxae, t1_xaee, optimize = einsum_type)
    temp += 1/2 * einsum('Rijab,Pixb,jxQa->RPQ', Y_KLCD, t1_xxae, t1_xaee, optimize = einsum_type)
    temp -= einsum('Rijab,Pixb,jxaQ->RPQ', Y_KLCD, t1_xxae, t1_xaee, optimize = einsum_type)
    temp += einsum('Rijab,iPxQ,jxab->RPQ', Y_KLCD, t1_xxae, t1_xaee, optimize = einsum_type)
    temp -= 2 * einsum('Rijab,iPxQ,jxba->RPQ', Y_KLCD, t1_xxae, t1_xaee, optimize = einsum_type)
    temp += 1/2 * einsum('Rijab,iPxa,jxQb->RPQ', Y_KLCD, t1_xxae, t1_xaee, optimize = einsum_type)
    temp -= einsum('Rijab,iPxa,jxbQ->RPQ', Y_KLCD, t1_xxae, t1_xaee, optimize = einsum_type)
    temp -= einsum('Rijab,iPxb,jxQa->RPQ', Y_KLCD, t1_xxae, t1_xaee, optimize = einsum_type)
    temp += 1/2 * einsum('Rijab,iPxb,jxaQ->RPQ', Y_KLCD, t1_xxae, t1_xaee, optimize = einsum_type)
    temp += einsum('Rijab,ijQa,Pb->RPQ', Y_KLCD, t1_xxee, t1_xe, optimize = einsum_type)
    temp -= 2 * einsum('Rijab,jiQa,Pb->RPQ', Y_KLCD, t1_xxee, t1_xe, optimize = einsum_type)
    temp -= einsum('Rijab,jixQ,Pxab->RPQ', Y_KLCD, t1_xxae, t1_xaee, optimize = einsum_type)
    temp += 1/2 * einsum('Rijab,jixQ,Pxba->RPQ', Y_KLCD, t1_xxae, t1_xaee, optimize = einsum_type)
    temp += 2 * einsum('Rijab,jixa,PxQb->RPQ', Y_KLCD, t1_xxae, t1_xaee, optimize = einsum_type)
    temp -= einsum('Rijab,jixa,PxbQ->RPQ', Y_KLCD, t1_xxae, t1_xaee, optimize = einsum_type)
    temp -= einsum('Rijab,jixb,PxQa->RPQ', Y_KLCD, t1_xxae, t1_xaee, optimize = einsum_type)
    temp += 1/2 * einsum('Rijab,jixb,PxaQ->RPQ', Y_KLCD, t1_xxae, t1_xaee, optimize = einsum_type)
    temp += 1/2 * einsum('RPiab,ijab,jxQy,yx->RPQ', Y_KLCD, t1_xxee, t1_xaea, rdm_ca, optimize = einsum_type)
    temp -= 1/4 * einsum('RPiab,ijab,jxyQ,yx->RPQ', Y_KLCD, t1_xxee, t1_xaae, rdm_ca, optimize = einsum_type)
    temp -= einsum('RPiab,ijba,jxQy,yx->RPQ', Y_KLCD, t1_xxee, t1_xaea, rdm_ca, optimize = einsum_type)
    temp += 1/2 * einsum('RPiab,ijba,jxyQ,yx->RPQ', Y_KLCD, t1_xxee, t1_xaae, rdm_ca, optimize = einsum_type)
    temp += 1/2 * einsum('RPiab,ijab,jxQy,yx->RPQ', Y_KLCD, t1_xvee, t1_vaea, rdm_ca, optimize = einsum_type)
    temp -= 1/4 * einsum('RPiab,ijab,jxyQ,yx->RPQ', Y_KLCD, t1_xvee, t1_vaae, rdm_ca, optimize = einsum_type)
    temp -= einsum('RPiab,ijba,jxQy,yx->RPQ', Y_KLCD, t1_xvee, t1_vaea, rdm_ca, optimize = einsum_type)
    temp += 1/2 * einsum('RPiab,ijba,jxyQ,yx->RPQ', Y_KLCD, t1_xvee, t1_vaae, rdm_ca, optimize = einsum_type)
    temp -= 1/4 * einsum('RPiab,ixab,xyzQ,zy->RPQ', Y_KLCD, t1_xaee, t1_aaae, rdm_ca, optimize = einsum_type)
    temp += 1/2 * einsum('RPiab,ixab,yxzQ,zy->RPQ', Y_KLCD, t1_xaee, t1_aaae, rdm_ca, optimize = einsum_type)
    temp += 1/2 * einsum('RPiab,ixba,xyzQ,zy->RPQ', Y_KLCD, t1_xaee, t1_aaae, rdm_ca, optimize = einsum_type)
    temp -= einsum('RPiab,ixba,yxzQ,zy->RPQ', Y_KLCD, t1_xaee, t1_aaae, rdm_ca, optimize = einsum_type)
    temp += 1/2 * einsum('RijQa,ijab,Pxby,xy->RPQ', Y_KLCD, t1_xxee, t1_xaea, rdm_ca, optimize = einsum_type)
    temp -= 1/4 * einsum('RijQa,ijab,Pxyb,xy->RPQ', Y_KLCD, t1_xxee, t1_xaae, rdm_ca, optimize = einsum_type)
    temp -= einsum('RijQa,ijba,Pxby,xy->RPQ', Y_KLCD, t1_xxee, t1_xaea, rdm_ca, optimize = einsum_type)
    temp += 1/2 * einsum('RijQa,ijba,Pxyb,xy->RPQ', Y_KLCD, t1_xxee, t1_xaae, rdm_ca, optimize = einsum_type)
    temp -= einsum('RijQa,ijxa,Pyxz,yz->RPQ', Y_KLCD, t1_xxae, t1_xaaa, rdm_ca, optimize = einsum_type)
    temp += 1/2 * einsum('RijQa,ijxa,Pyzx,yz->RPQ', Y_KLCD, t1_xxae, t1_xaaa, rdm_ca, optimize = einsum_type)
    temp += 1/2 * einsum('RijQa,jixa,Pyxz,yz->RPQ', Y_KLCD, t1_xxae, t1_xaaa, rdm_ca, optimize = einsum_type)
    temp -= 1/4 * einsum('RijQa,jixa,Pyzx,yz->RPQ', Y_KLCD, t1_xxae, t1_xaaa, rdm_ca, optimize = einsum_type)
    temp += einsum('Rijab,Piab,jxQy,yx->RPQ', Y_KLCD, t1_xxee, t1_xaea, rdm_ca, optimize = einsum_type)
    temp -= 1/2 * einsum('Rijab,Piab,jxyQ,yx->RPQ', Y_KLCD, t1_xxee, t1_xaae, rdm_ca, optimize = einsum_type)
    temp -= 2 * einsum('Rijab,Piba,jxQy,yx->RPQ', Y_KLCD, t1_xxee, t1_xaea, rdm_ca, optimize = einsum_type)
    temp += einsum('Rijab,Piba,jxyQ,yx->RPQ', Y_KLCD, t1_xxee, t1_xaae, rdm_ca, optimize = einsum_type)
    temp += einsum('Rijab,Pixa,jyQb,xy->RPQ', Y_KLCD, t1_xxae, t1_xaee, rdm_ca, optimize = einsum_type)
    temp -= 2 * einsum('Rijab,Pixa,jybQ,xy->RPQ', Y_KLCD, t1_xxae, t1_xaee, rdm_ca, optimize = einsum_type)
    temp -= 1/2 * einsum('Rijab,Pixb,jyQa,xy->RPQ', Y_KLCD, t1_xxae, t1_xaee, rdm_ca, optimize = einsum_type)
    temp += einsum('Rijab,Pixb,jyaQ,xy->RPQ', Y_KLCD, t1_xxae, t1_xaee, rdm_ca, optimize = einsum_type)
    temp -= 1/2 * einsum('Rijab,iPxa,jyQb,xy->RPQ', Y_KLCD, t1_xxae, t1_xaee, rdm_ca, optimize = einsum_type)
    temp += einsum('Rijab,iPxa,jybQ,xy->RPQ', Y_KLCD, t1_xxae, t1_xaee, rdm_ca, optimize = einsum_type)
    temp += einsum('Rijab,iPxb,jyQa,xy->RPQ', Y_KLCD, t1_xxae, t1_xaee, rdm_ca, optimize = einsum_type)
    temp -= 1/2 * einsum('Rijab,iPxb,jyaQ,xy->RPQ', Y_KLCD, t1_xxae, t1_xaee, rdm_ca, optimize = einsum_type)
    temp += einsum('Rijab,ijQa,Pxby,xy->RPQ', Y_KLCD, t1_xxee, t1_xaea, rdm_ca, optimize = einsum_type)
    temp -= 1/2 * einsum('Rijab,ijQa,Pxyb,xy->RPQ', Y_KLCD, t1_xxee, t1_xaae, rdm_ca, optimize = einsum_type)
    temp -= 2 * einsum('Rijab,jiQa,Pxby,xy->RPQ', Y_KLCD, t1_xxee, t1_xaea, rdm_ca, optimize = einsum_type)
    temp += einsum('Rijab,jiQa,Pxyb,xy->RPQ', Y_KLCD, t1_xxee, t1_xaae, rdm_ca, optimize = einsum_type)
    temp += einsum('Rijab,jixQ,Pyab,xy->RPQ', Y_KLCD, t1_xxae, t1_xaee, rdm_ca, optimize = einsum_type)
    temp -= 1/2 * einsum('Rijab,jixQ,Pyba,xy->RPQ', Y_KLCD, t1_xxae, t1_xaee, rdm_ca, optimize = einsum_type)
    TY[:, s_c:f_c, s_e:f_e] += temp

    temp = 1/2 * einsum('RijQa,ijab,Pb->RPQ', Y_KLCD, t1_xxee, t1_ve, optimize = einsum_type)
    temp -= einsum('RijQa,ijba,Pb->RPQ', Y_KLCD, t1_xxee, t1_ve, optimize = einsum_type)
    temp -= einsum('RijQa,ijxa,Px->RPQ', Y_KLCD, t1_xxae, t1_va, optimize = einsum_type)
    temp += 1/2 * einsum('RijQa,jixa,Px->RPQ', Y_KLCD, t1_xxae, t1_va, optimize = einsum_type)
    temp += einsum('Rijab,Piab,jQ->RPQ', Y_KLCD, t1_vxee, t1_xe, optimize = einsum_type)
    temp -= 2 * einsum('Rijab,Piba,jQ->RPQ', Y_KLCD, t1_vxee, t1_xe, optimize = einsum_type)
    temp -= 1/2 * einsum('Rijab,PixQ,jxab->RPQ', Y_KLCD, t1_vxae, t1_xaee, optimize = einsum_type)
    temp += einsum('Rijab,PixQ,jxba->RPQ', Y_KLCD, t1_vxae, t1_xaee, optimize = einsum_type)
    temp -= einsum('Rijab,Pixa,jxQb->RPQ', Y_KLCD, t1_vxae, t1_xaee, optimize = einsum_type)
    temp += 2 * einsum('Rijab,Pixa,jxbQ->RPQ', Y_KLCD, t1_vxae, t1_xaee, optimize = einsum_type)
    temp += 1/2 * einsum('Rijab,Pixb,jxQa->RPQ', Y_KLCD, t1_vxae, t1_xaee, optimize = einsum_type)
    temp -= einsum('Rijab,Pixb,jxaQ->RPQ', Y_KLCD, t1_vxae, t1_xaee, optimize = einsum_type)
    temp += einsum('Rijab,iPxQ,jxab->RPQ', Y_KLCD, t1_xvae, t1_xaee, optimize = einsum_type)
    temp -= 2 * einsum('Rijab,iPxQ,jxba->RPQ', Y_KLCD, t1_xvae, t1_xaee, optimize = einsum_type)
    temp += 1/2 * einsum('Rijab,iPxa,jxQb->RPQ', Y_KLCD, t1_xvae, t1_xaee, optimize = einsum_type)
    temp -= einsum('Rijab,iPxa,jxbQ->RPQ', Y_KLCD, t1_xvae, t1_xaee, optimize = einsum_type)
    temp -= einsum('Rijab,iPxb,jxQa->RPQ', Y_KLCD, t1_xvae, t1_xaee, optimize = einsum_type)
    temp += 1/2 * einsum('Rijab,iPxb,jxaQ->RPQ', Y_KLCD, t1_xvae, t1_xaee, optimize = einsum_type)
    temp += einsum('Rijab,ijQa,Pb->RPQ', Y_KLCD, t1_xxee, t1_ve, optimize = einsum_type)
    temp -= 2 * einsum('Rijab,jiQa,Pb->RPQ', Y_KLCD, t1_xxee, t1_ve, optimize = einsum_type)
    temp -= einsum('Rijab,jixQ,Pxab->RPQ', Y_KLCD, t1_xxae, t1_vaee, optimize = einsum_type)
    temp += 1/2 * einsum('Rijab,jixQ,Pxba->RPQ', Y_KLCD, t1_xxae, t1_vaee, optimize = einsum_type)
    temp += 2 * einsum('Rijab,jixa,PxQb->RPQ', Y_KLCD, t1_xxae, t1_vaee, optimize = einsum_type)
    temp -= einsum('Rijab,jixa,PxbQ->RPQ', Y_KLCD, t1_xxae, t1_vaee, optimize = einsum_type)
    temp -= einsum('Rijab,jixb,PxQa->RPQ', Y_KLCD, t1_xxae, t1_vaee, optimize = einsum_type)
    temp += 1/2 * einsum('Rijab,jixb,PxaQ->RPQ', Y_KLCD, t1_xxae, t1_vaee, optimize = einsum_type)
    temp += 1/2 * einsum('RijQa,ijab,Pxby,xy->RPQ', Y_KLCD, t1_xxee, t1_vaea, rdm_ca, optimize = einsum_type)
    temp -= 1/4 * einsum('RijQa,ijab,Pxyb,xy->RPQ', Y_KLCD, t1_xxee, t1_vaae, rdm_ca, optimize = einsum_type)
    temp -= einsum('RijQa,ijba,Pxby,xy->RPQ', Y_KLCD, t1_xxee, t1_vaea, rdm_ca, optimize = einsum_type)
    temp += 1/2 * einsum('RijQa,ijba,Pxyb,xy->RPQ', Y_KLCD, t1_xxee, t1_vaae, rdm_ca, optimize = einsum_type)
    temp -= einsum('RijQa,ijxa,Pyxz,yz->RPQ', Y_KLCD, t1_xxae, t1_vaaa, rdm_ca, optimize = einsum_type)
    temp += 1/2 * einsum('RijQa,ijxa,Pyzx,yz->RPQ', Y_KLCD, t1_xxae, t1_vaaa, rdm_ca, optimize = einsum_type)
    temp += 1/2 * einsum('RijQa,jixa,Pyxz,yz->RPQ', Y_KLCD, t1_xxae, t1_vaaa, rdm_ca, optimize = einsum_type)
    temp -= 1/4 * einsum('RijQa,jixa,Pyzx,yz->RPQ', Y_KLCD, t1_xxae, t1_vaaa, rdm_ca, optimize = einsum_type)
    temp += einsum('Rijab,Piab,jxQy,yx->RPQ', Y_KLCD, t1_vxee, t1_xaea, rdm_ca, optimize = einsum_type)
    temp -= 1/2 * einsum('Rijab,Piab,jxyQ,yx->RPQ', Y_KLCD, t1_vxee, t1_xaae, rdm_ca, optimize = einsum_type)
    temp -= 2 * einsum('Rijab,Piba,jxQy,yx->RPQ', Y_KLCD, t1_vxee, t1_xaea, rdm_ca, optimize = einsum_type)
    temp += einsum('Rijab,Piba,jxyQ,yx->RPQ', Y_KLCD, t1_vxee, t1_xaae, rdm_ca, optimize = einsum_type)
    temp += einsum('Rijab,Pixa,jyQb,xy->RPQ', Y_KLCD, t1_vxae, t1_xaee, rdm_ca, optimize = einsum_type)
    temp -= 2 * einsum('Rijab,Pixa,jybQ,xy->RPQ', Y_KLCD, t1_vxae, t1_xaee, rdm_ca, optimize = einsum_type)
    temp -= 1/2 * einsum('Rijab,Pixb,jyQa,xy->RPQ', Y_KLCD, t1_vxae, t1_xaee, rdm_ca, optimize = einsum_type)
    temp += einsum('Rijab,Pixb,jyaQ,xy->RPQ', Y_KLCD, t1_vxae, t1_xaee, rdm_ca, optimize = einsum_type)
    temp -= 1/2 * einsum('Rijab,iPxa,jyQb,xy->RPQ', Y_KLCD, t1_xvae, t1_xaee, rdm_ca, optimize = einsum_type)
    temp += einsum('Rijab,iPxa,jybQ,xy->RPQ', Y_KLCD, t1_xvae, t1_xaee, rdm_ca, optimize = einsum_type)
    temp += einsum('Rijab,iPxb,jyQa,xy->RPQ', Y_KLCD, t1_xvae, t1_xaee, rdm_ca, optimize = einsum_type)
    temp -= 1/2 * einsum('Rijab,iPxb,jyaQ,xy->RPQ', Y_KLCD, t1_xvae, t1_xaee, rdm_ca, optimize = einsum_type)
    temp += einsum('Rijab,ijQa,Pxby,xy->RPQ', Y_KLCD, t1_xxee, t1_vaea, rdm_ca, optimize = einsum_type)
    temp -= 1/2 * einsum('Rijab,ijQa,Pxyb,xy->RPQ', Y_KLCD, t1_xxee, t1_vaae, rdm_ca, optimize = einsum_type)
    temp -= 2 * einsum('Rijab,jiQa,Pxby,xy->RPQ', Y_KLCD, t1_xxee, t1_vaea, rdm_ca, optimize = einsum_type)
    temp += einsum('Rijab,jiQa,Pxyb,xy->RPQ', Y_KLCD, t1_xxee, t1_vaae, rdm_ca, optimize = einsum_type)
    temp += einsum('Rijab,jixQ,Pyab,xy->RPQ', Y_KLCD, t1_xxae, t1_vaee, rdm_ca, optimize = einsum_type)
    temp -= 1/2 * einsum('Rijab,jixQ,Pyba,xy->RPQ', Y_KLCD, t1_xxae, t1_vaee, rdm_ca, optimize = einsum_type)
    TY[:, s_v:f_v, s_e:f_e] += temp

    temp =- einsum('RijQa,ijPx,xa->RPQ', Y_KLCD, t1_xxaa, t1_ae, optimize = einsum_type)
    temp += 1/2 * einsum('RijQa,ijab,Pb->RPQ', Y_KLCD, t1_xxee, t1_ae, optimize = einsum_type)
    temp -= einsum('RijQa,ijba,Pb->RPQ', Y_KLCD, t1_xxee, t1_ae, optimize = einsum_type)
    temp += einsum('RijQa,ijxy,xyPa->RPQ', Y_KLCD, t1_xxaa, t1_aaae, optimize = einsum_type)
    temp -= 1/2 * einsum('RijQa,ijxy,yxPa->RPQ', Y_KLCD, t1_xxaa, t1_aaae, optimize = einsum_type)
    temp -= 1/2 * einsum('RijQa,ix,jxPa->RPQ', Y_KLCD, t1_xa, t1_xaae, optimize = einsum_type)
    temp += einsum('RijQa,ix,jxaP->RPQ', Y_KLCD, t1_xa, t1_xaea, optimize = einsum_type)
    temp += einsum('RijQa,ixPa,jx->RPQ', Y_KLCD, t1_xaae, t1_xa, optimize = einsum_type)
    temp -= 1/2 * einsum('RijQa,ixaP,jx->RPQ', Y_KLCD, t1_xaea, t1_xa, optimize = einsum_type)
    temp += 1/2 * einsum('RijQa,jiPx,xa->RPQ', Y_KLCD, t1_xxaa, t1_ae, optimize = einsum_type)
    temp -= 2 * einsum('Rijab,iPab,jQ->RPQ', Y_KLCD, t1_xaee, t1_xe, optimize = einsum_type)
    temp += einsum('Rijab,iPba,jQ->RPQ', Y_KLCD, t1_xaee, t1_xe, optimize = einsum_type)
    temp += einsum('Rijab,ijQa,Pb->RPQ', Y_KLCD, t1_xxee, t1_ae, optimize = einsum_type)
    temp -= 2 * einsum('Rijab,jiQa,Pb->RPQ', Y_KLCD, t1_xxee, t1_ae, optimize = einsum_type)
    temp -= 2 * einsum('Rijab,jixQ,Pxab->RPQ', Y_KLCD, t1_xxae, t1_aaee, optimize = einsum_type)
    temp += einsum('Rijab,jixQ,Pxba->RPQ', Y_KLCD, t1_xxae, t1_aaee, optimize = einsum_type)
    temp += 1/2 * einsum('RijQa,ijPx,xyza,zy->RPQ', Y_KLCD, t1_xxaa, t1_aaae, rdm_ca, optimize = einsum_type)
    temp -= einsum('RijQa,ijPx,yxza,zy->RPQ', Y_KLCD, t1_xxaa, t1_aaae, rdm_ca, optimize = einsum_type)
    temp -= 1/4 * einsum('RijQa,ijab,Pxyb,xy->RPQ', Y_KLCD, t1_xxee, t1_aaae, rdm_ca, optimize = einsum_type)
    temp += 1/2 * einsum('RijQa,ijab,xPyb,xy->RPQ', Y_KLCD, t1_xxee, t1_aaae, rdm_ca, optimize = einsum_type)
    temp += 1/2 * einsum('RijQa,ijba,Pxyb,xy->RPQ', Y_KLCD, t1_xxee, t1_aaae, rdm_ca, optimize = einsum_type)
    temp -= einsum('RijQa,ijba,xPyb,xy->RPQ', Y_KLCD, t1_xxee, t1_aaae, rdm_ca, optimize = einsum_type)
    temp -= 1/2 * einsum('RijQa,ijxy,xzPa,yz->RPQ', Y_KLCD, t1_xxaa, t1_aaae, rdm_ca, optimize = einsum_type)
    temp += 1/4 * einsum('RijQa,ijxy,yzPa,xz->RPQ', Y_KLCD, t1_xxaa, t1_aaae, rdm_ca, optimize = einsum_type)
    temp += 1/4 * einsum('RijQa,ijxy,zxPa,yz->RPQ', Y_KLCD, t1_xxaa, t1_aaae, rdm_ca, optimize = einsum_type)
    temp -= 1/2 * einsum('RijQa,ijxy,zyPa,xz->RPQ', Y_KLCD, t1_xxaa, t1_aaae, rdm_ca, optimize = einsum_type)
    temp += einsum('RijQa,ixPa,jyxz,yz->RPQ', Y_KLCD, t1_xaae, t1_xaaa, rdm_ca, optimize = einsum_type)
    temp -= 1/2 * einsum('RijQa,ixPa,jyzx,yz->RPQ', Y_KLCD, t1_xaae, t1_xaaa, rdm_ca, optimize = einsum_type)
    temp -= einsum('RijQa,ixPy,jyaz,xz->RPQ', Y_KLCD, t1_xaaa, t1_xaea, rdm_ca, optimize = einsum_type)
    temp += 1/2 * einsum('RijQa,ixPy,jyza,xz->RPQ', Y_KLCD, t1_xaaa, t1_xaae, rdm_ca, optimize = einsum_type)
    temp += einsum('RijQa,ixPy,jzax,yz->RPQ', Y_KLCD, t1_xaaa, t1_xaea, rdm_ca, optimize = einsum_type)
    temp -= 1/2 * einsum('RijQa,ixPy,jzxa,yz->RPQ', Y_KLCD, t1_xaaa, t1_xaae, rdm_ca, optimize = einsum_type)
    temp -= 1/2 * einsum('RijQa,ixaP,jyxz,yz->RPQ', Y_KLCD, t1_xaea, t1_xaaa, rdm_ca, optimize = einsum_type)
    temp += 1/4 * einsum('RijQa,ixaP,jyzx,yz->RPQ', Y_KLCD, t1_xaea, t1_xaaa, rdm_ca, optimize = einsum_type)
    temp -= 1/2 * einsum('RijQa,ixay,jyPz,xz->RPQ', Y_KLCD, t1_xaea, t1_xaaa, rdm_ca, optimize = einsum_type)
    temp += 1/4 * einsum('RijQa,ixay,jyzP,xz->RPQ', Y_KLCD, t1_xaea, t1_xaaa, rdm_ca, optimize = einsum_type)
    temp += 1/2 * einsum('RijQa,ixay,jzPx,yz->RPQ', Y_KLCD, t1_xaea, t1_xaaa, rdm_ca, optimize = einsum_type)
    temp -= 1/4 * einsum('RijQa,ixay,jzxP,yz->RPQ', Y_KLCD, t1_xaea, t1_xaaa, rdm_ca, optimize = einsum_type)
    temp += 1/2 * einsum('RijQa,ixyP,jyaz,xz->RPQ', Y_KLCD, t1_xaaa, t1_xaea, rdm_ca, optimize = einsum_type)
    temp -= 1/4 * einsum('RijQa,ixyP,jyza,xz->RPQ', Y_KLCD, t1_xaaa, t1_xaae, rdm_ca, optimize = einsum_type)
    temp -= 1/2 * einsum('RijQa,ixyP,jzax,yz->RPQ', Y_KLCD, t1_xaaa, t1_xaea, rdm_ca, optimize = einsum_type)
    temp += 1/4 * einsum('RijQa,ixyP,jzxa,yz->RPQ', Y_KLCD, t1_xaaa, t1_xaae, rdm_ca, optimize = einsum_type)
    temp += 1/4 * einsum('RijQa,ixya,jyPz,xz->RPQ', Y_KLCD, t1_xaae, t1_xaaa, rdm_ca, optimize = einsum_type)
    temp -= 1/2 * einsum('RijQa,ixya,jyzP,xz->RPQ', Y_KLCD, t1_xaae, t1_xaaa, rdm_ca, optimize = einsum_type)
    temp -= 1/4 * einsum('RijQa,ixya,jzPx,yz->RPQ', Y_KLCD, t1_xaae, t1_xaaa, rdm_ca, optimize = einsum_type)
    temp += 1/2 * einsum('RijQa,ixya,jzxP,yz->RPQ', Y_KLCD, t1_xaae, t1_xaaa, rdm_ca, optimize = einsum_type)
    temp -= 1/2 * einsum('RijQa,ixyz,jyPa,xz->RPQ', Y_KLCD, t1_xaaa, t1_xaae, rdm_ca, optimize = einsum_type)
    temp += einsum('RijQa,ixyz,jyaP,xz->RPQ', Y_KLCD, t1_xaaa, t1_xaea, rdm_ca, optimize = einsum_type)
    temp += 1/4 * einsum('RijQa,ixyz,jzPa,xy->RPQ', Y_KLCD, t1_xaaa, t1_xaae, rdm_ca, optimize = einsum_type)
    temp -= 1/2 * einsum('RijQa,ixyz,jzaP,xy->RPQ', Y_KLCD, t1_xaaa, t1_xaea, rdm_ca, optimize = einsum_type)
    temp -= 1/4 * einsum('RijQa,jiPx,xyza,zy->RPQ', Y_KLCD, t1_xxaa, t1_aaae, rdm_ca, optimize = einsum_type)
    temp += 1/2 * einsum('RijQa,jiPx,yxza,zy->RPQ', Y_KLCD, t1_xxaa, t1_aaae, rdm_ca, optimize = einsum_type)
    temp -= 2 * einsum('Rijab,iPab,jxQy,yx->RPQ', Y_KLCD, t1_xaee, t1_xaea, rdm_ca, optimize = einsum_type)
    temp += einsum('Rijab,iPab,jxyQ,yx->RPQ', Y_KLCD, t1_xaee, t1_xaae, rdm_ca, optimize = einsum_type)
    temp += einsum('Rijab,iPax,jyQb,xy->RPQ', Y_KLCD, t1_xaea, t1_xaee, rdm_ca, optimize = einsum_type)
    temp -= 2 * einsum('Rijab,iPax,jybQ,xy->RPQ', Y_KLCD, t1_xaea, t1_xaee, rdm_ca, optimize = einsum_type)
    temp += einsum('Rijab,iPba,jxQy,yx->RPQ', Y_KLCD, t1_xaee, t1_xaea, rdm_ca, optimize = einsum_type)
    temp -= 1/2 * einsum('Rijab,iPba,jxyQ,yx->RPQ', Y_KLCD, t1_xaee, t1_xaae, rdm_ca, optimize = einsum_type)
    temp -= 1/2 * einsum('Rijab,iPbx,jyQa,xy->RPQ', Y_KLCD, t1_xaea, t1_xaee, rdm_ca, optimize = einsum_type)
    temp += einsum('Rijab,iPbx,jyaQ,xy->RPQ', Y_KLCD, t1_xaea, t1_xaee, rdm_ca, optimize = einsum_type)
    temp -= 1/2 * einsum('Rijab,iPxa,jyQb,xy->RPQ', Y_KLCD, t1_xaae, t1_xaee, rdm_ca, optimize = einsum_type)
    temp += einsum('Rijab,iPxa,jybQ,xy->RPQ', Y_KLCD, t1_xaae, t1_xaee, rdm_ca, optimize = einsum_type)
    temp += einsum('Rijab,iPxb,jyQa,xy->RPQ', Y_KLCD, t1_xaae, t1_xaee, rdm_ca, optimize = einsum_type)
    temp -= 1/2 * einsum('Rijab,iPxb,jyaQ,xy->RPQ', Y_KLCD, t1_xaae, t1_xaee, rdm_ca, optimize = einsum_type)
    temp -= 1/2 * einsum('Rijab,ijQa,Pxyb,xy->RPQ', Y_KLCD, t1_xxee, t1_aaae, rdm_ca, optimize = einsum_type)
    temp += einsum('Rijab,ijQa,xPyb,xy->RPQ', Y_KLCD, t1_xxee, t1_aaae, rdm_ca, optimize = einsum_type)
    temp -= 1/2 * einsum('Rijab,ixQa,jybx,Py->RPQ', Y_KLCD, t1_xaee, t1_xaea, rdm_ca, optimize = einsum_type)
    temp += 1/4 * einsum('Rijab,ixQa,jyxb,Py->RPQ', Y_KLCD, t1_xaee, t1_xaae, rdm_ca, optimize = einsum_type)
    temp += 1/4 * einsum('Rijab,ixQb,jyax,Py->RPQ', Y_KLCD, t1_xaee, t1_xaea, rdm_ca, optimize = einsum_type)
    temp -= 1/2 * einsum('Rijab,ixQb,jyxa,Py->RPQ', Y_KLCD, t1_xaee, t1_xaae, rdm_ca, optimize = einsum_type)
    temp -= 1/4 * einsum('Rijab,ixQy,jyab,Px->RPQ', Y_KLCD, t1_xaea, t1_xaee, rdm_ca, optimize = einsum_type)
    temp += 1/2 * einsum('Rijab,ixQy,jyba,Px->RPQ', Y_KLCD, t1_xaea, t1_xaee, rdm_ca, optimize = einsum_type)
    temp += einsum('Rijab,ixaQ,jybx,Py->RPQ', Y_KLCD, t1_xaee, t1_xaea, rdm_ca, optimize = einsum_type)
    temp -= 1/2 * einsum('Rijab,ixaQ,jyxb,Py->RPQ', Y_KLCD, t1_xaee, t1_xaae, rdm_ca, optimize = einsum_type)
    temp -= 1/2 * einsum('Rijab,ixbQ,jyax,Py->RPQ', Y_KLCD, t1_xaee, t1_xaea, rdm_ca, optimize = einsum_type)
    temp += 1/4 * einsum('Rijab,ixbQ,jyxa,Py->RPQ', Y_KLCD, t1_xaee, t1_xaae, rdm_ca, optimize = einsum_type)
    temp += 1/2 * einsum('Rijab,ixyQ,jyab,Px->RPQ', Y_KLCD, t1_xaae, t1_xaee, rdm_ca, optimize = einsum_type)
    temp -= einsum('Rijab,ixyQ,jyba,Px->RPQ', Y_KLCD, t1_xaae, t1_xaee, rdm_ca, optimize = einsum_type)
    temp += einsum('Rijab,jiQa,Pxyb,xy->RPQ', Y_KLCD, t1_xxee, t1_aaae, rdm_ca, optimize = einsum_type)
    temp -= 2 * einsum('Rijab,jiQa,xPyb,xy->RPQ', Y_KLCD, t1_xxee, t1_aaae, rdm_ca, optimize = einsum_type)
    temp += einsum('Rijab,jixQ,Pyab,xy->RPQ', Y_KLCD, t1_xxae, t1_aaee, rdm_ca, optimize = einsum_type)
    temp -= 1/2 * einsum('Rijab,jixQ,Pyba,xy->RPQ', Y_KLCD, t1_xxae, t1_aaee, rdm_ca, optimize = einsum_type)
    temp -= 1/4 * einsum('Rijab,jixQ,xyab,Py->RPQ', Y_KLCD, t1_xxae, t1_aaee, rdm_ca, optimize = einsum_type)
    temp += 1/2 * einsum('Rijab,jixQ,yxab,Py->RPQ', Y_KLCD, t1_xxae, t1_aaee, rdm_ca, optimize = einsum_type)
    temp -= 1/2 * einsum('Rijab,jixa,xyQb,Py->RPQ', Y_KLCD, t1_xxae, t1_aaee, rdm_ca, optimize = einsum_type)
    temp += einsum('Rijab,jixa,yxQb,Py->RPQ', Y_KLCD, t1_xxae, t1_aaee, rdm_ca, optimize = einsum_type)
    temp += 1/4 * einsum('Rijab,jixb,xyQa,Py->RPQ', Y_KLCD, t1_xxae, t1_aaee, rdm_ca, optimize = einsum_type)
    temp -= 1/2 * einsum('Rijab,jixb,yxQa,Py->RPQ', Y_KLCD, t1_xxae, t1_aaee, rdm_ca, optimize = einsum_type)
    TY[:, s_a:f_a, s_e:f_e] += temp

    mr_adc.log.timer_debug("computing T q2-h1 CCEE", *cput1)